### ISSUE TITLE
GD-103: Provide a signal collector

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

The existing `assert_signal()` only waits for a signal to be emitted on a particular instance and only during the assert call.
To test if an instance has emitted signals since its creation, we need a way to collect all signals.
A signal collector helps to define the start and end point of collecting signals and the test author can decide when to test for a particular signal. 

### Dev notes
check existing `SignalCollector` at `GdUnitSignalAssertImpl`

**Describe alternatives you've considered**
I already implemented it here, needs to be extract and documented
(https://github.com/MikeSchulze/gdUnit4/pull/102/files#:~:text=class%20GdUnitSignalCollector%3A,new(instance))

**Comment by monkeez** [comment]
Are there any other work arounds for this currently?

I have a test I'm trying to run where a bunch of signals will be emitted on a number of nodes. I then need to check that all of these signals have emitted and nothing else.

**Comment by MikeSchulze** [comment]
you can use a spy and verify if the signals emitted

**Comment by monkeez** [comment]
When I try something like that I'm getting an error:

```
line <n/a>: Expecting interaction on:
	'emit_signal(my_signal :String)'	1 time's
But found interactions on:
	'do_it()'	1 time's
```

![image](https://user-images.githubusercontent.com/5214414/223255928-75078bb0-1b41-49b2-b07a-f4dfbe5fbf65.png)

**Comment by MikeSchulze** [comment]
This was just an example ;)
There exists no class `MyEmitter` on your project.

**Comment by monkeez** [comment]
Yeah `MyEmiter` is in `blah.gd`:

```
class_name MyEmitter
extends Node


signal my_signal


func do_it() -> void:
	my_signal.emit()
```

Was just trying to get a very simple version to work before trying on my main project.

**Comment by MikeSchulze** [comment]
hm interesting, i will check whats goes wrong

**Comment by MikeSchulze** [comment]
ok its the issue with the not allowed override core functions since Godot4
https://github.com/MikeSchulze/gdUnit4/issues/42

The problem is `emit_signal` is a core function and the mock and spy are broken because I have no chance to track the interactions on these functions.

Too bad, so you have to wait until this ticket is ready
