### ISSUE TITLE
Trying to return an array of type "Array" where expected return type is "Array[GdUnitProperty]"

### ISSUE THREAD

**Issue by lostptr** [MikeSchulze/gdUnit4#113]
**The used Godot version:**
Godot v4.0 - RC 1

**OS including version:**
Windows 10

**Describe the bug**
Editor console is printing the following error when cliclink on "GdUnit Tools":
> res://addons/gdUnit4/src/core/GdUnitSettings.gd:176 - Trying to return an array of type "Array" where expected return type is "Array[GdUnitProperty]".

**Steps to Reproduce**
Create a new project just like [this example](https://mikeschulze.github.io/gdUnit3/first_steps/firstTest/).
Go to the GdUnit tab and click on "GdUnit Tools" as shown in this image.
![image](https://user-images.githubusercontent.com/21160216/218234268-c7edf4cd-c610-4d84-9510-fe91b54258cc.png)

**Minimal reproduction project:**
[test.zip](https://github.com/MikeSchulze/gdUnit4/files/10712369/test.zip)

**Comment by MikeSchulze** [comment]
Have you used the latest version from master?
You need actually to update GdUnit4 manually by downloading the latest version from master branch

**Comment by lostptr** [comment]
Oh I see. I will do that and confirm if the bug still happends

**Comment by MikeSchulze** [comment]
> Oh I see. I will do that and confirm if the bug still happens

This is already fixed ;)
This error only occurs when using outdated GdUnit4 version.
