### ISSUE TITLE
GD-140: Add button to run overall tests to the inspector toolbar

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#140]
**Is your feature request related to a problem? Please describe.**
I want to run all my test of the current selected test suite from the inspector.

**Describe the solution you'd like**
Add a new button (>>) to run run all tests.

**Describe alternatives you've considered**
- right click in your test suite (not on the test case) and use contect menu to run all tests
- select the test suite root node in the inspector and right click to use contect menu to run all tests

**Additional context**

[discussions](https://github.com/MikeSchulze/gdUnit4/discussions/138)

**Comment by Structed** [comment]
Thanks so much for implementing it!
