### ISSUE TITLE
GD-142: Update jquery (Windows bitdefender)

### ISSUE THREAD

**Issue by clemens-tolboom** [MikeSchulze/gdUnit4#142]
**The used GdUnit4 version:**

Downloading directly from https://github.com/MikeSchulze/gdUnit4/archive/refs/heads/master.zip

**The used Godot version:**

**OS including version:**

Window 10

**Describe the bug**

When downloading https://github.com/MikeSchulze/gdUnit4/archive/refs/heads/master.zip MS Bitdefender kicks in.

`<script src="https://code.jquery.com/jquery-3.3.1.js</script>`
This is reported as unsafe on ie https://security.snyk.io/package/npm/jquery/3.3.1

Guess "jQuery Core 3.6.4" needs testing?

**Steps to Reproduce**

**Minimal reproduction project:**

**Comment by MikeSchulze** [comment]
thank you for reporting this, i will update the jquery version soon
