### ISSUE TITLE
Request: Change the GdUnit4 project to use compatibility mode by default

### ISSUE THREAD

**Issue by ACG8** [MikeSchulze/gdUnit4#154]
**Is your feature request related to a problem? Please describe.**
Currently, the GdUnit4 project uses Forward+ mode. On my computer (and presumably other older computers), Forward+ does not work and I have to use Compatibility instead for GdUnit4. However, because GdUnit4 is saved with Forward+, it crashes the Godot4 engine when I load the project. Since I am unaware of any reason that Forward+ is necessary for working on GdUnit4, I would like to request a change to use Compatibility by default instead.

**Describe the solution you'd like**
I request that the GdUnit4 project switch from using Forward+ to using Compatibility mode. This involves the following change to the project.godot file:

```
[rendering]

environment/default_environment="res://default_env.tres"
```

becomes

```
[rendering]

renderer/rendering_method="gl_compatibility"
environment/default_environment="res://default_env.tres"
```

I recognize that this change does not affect end-users, only developers. The only reason I am asking is that it would make things more convenient for me and other potential contributors who might want to make pull requests in the future, or for users who want to play around with the code. Of course, if this creates an issue for your workflow, please disregard this.

**Describe alternatives you've considered**
The workaround is to open godot from the command line using the `--rendering-driver opengl3` flag, and then manually change from Forward+ to Compatibility before restarting the engine (or just manually edit the project.godot file).

**Comment by MikeSchulze** [comment]
Hi @ACG8 
Thanks for your suggestion, I understand your problem, but I want to use the default rendering mode as default, just to make sure that GdUnit runs with the default render settings.
I think the problem of older hardware is rather the exception.
Anyone developing with Godot4 who has this problem should be aware of it and can adapt the project to their development environment.
