### ISSUE TITLE
GD-164: Extend the array and dictionary asserts by `contains_same..` verification functions to handle compare objects by reference

### ISSUE THREAD

**Issue by ACG8** [MikeSchulze/gdUnit4#164]
**The used Godot version:**

Godot version 3.5
GdUnit3 version 2.4.1

**OS including version:**

Microsoft Windows 10 Home 10.0.19045 Build 19045

**Describe the bug**

The contains_exactly_in_any_order method for GdUnitArrayAssert does not work correctly for arrays of Resources. If an array of Resources contains Resources that are not supposed to be contained, the assertion does not fail.

**Steps to Reproduce**

1. Create a new test script file extending GdUnitTestSuite
2. Add the following test function:

```
func test_example():
	var r1 = Resource.new()
	var r2 = Resource.new()
	var a1 = [r1, r2]
	var a2 = [r1]
	assert_array(a1).contains_exactly_in_any_order(a2)
```

The expected behavior is that this test fails since a1 contains r2 in addition to r1. However, it passes instead.

I tested the same behavior with integers instead of resources and it worked properly:

```
func test_example():
	var a1 = [1, 2]
	var a2 = [1]
	assert_array(a1).contains_exactly_in_any_order(a2)
```

```
line <n/a>: Expecting contains exactly elements:
 1, 2
 do contains exactly (in any order)
 1
but some elements where not expected:
 2
```

**Comment by MikeSchulze** [comment]
I have now transferred this problem to GdUnit4 and will take a different approach to achieve the goal.

Adding a new setting is unfortunately not such a good idea, I have done some tests and the result is an incompatible API which would cause many tests to fail.

It is better to improve the functions to check 'equal' so as to explicitly determine the comparison.
So I will extend all equals functions with an extra optional argument with which you can influence the comparison method. 

``

example:
```
func test_object_is_equals_by_compare_mode():
	var node1 = RefCounted.new()
	var node2 = RefCounted.new()
	# will succed
	assert_object(node1).is_equal(node2)

	# will fail
	assert_object(node1).is_equal(node2, GdUnitAssert.OBJECT_REFERENCE_COMPARE)
```

![image](https://user-images.githubusercontent.com/347037/230720402-0fa7d15b-6219-42c1-bc9e-af1cfa0cad17.png)
