### ISSUE TITLE
GD-179: set_mouse_pos doesn't work correctly with window override + stretch mode canvas_item

### ISSUE THREAD

**Issue by Foxomat** [MikeSchulze/gdUnit4#179]
**The used GdUnit4 version:**
4.1.0

**The used Godot version:**
4.0.2.stable

**OS including version:**
Doesnt matter

**Describe the bug**
When using Window Override and Stretch Mode canvas_item, the method `scene_runner.set_mouse_pos()` doesn't set the mouse position to the desired position.

**Steps to Reproduce**
1. Create a blank project with GDUnit4
2. create a Scene with Node2D as root
3. create a test
```
# GdUnit generated TestSuite
class_name MainTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')

# TestSuite generated from
const __source = 'res://main.tscn'


func test_nothing() -> void:
	var _runner = scene_runner(__source)
	_runner.set_mouse_pos(Vector2(100, 100))
	print(_runner.invoke("get_global_mouse_position"))
```
5. When running this, it prints (100, 100), like expected
6. now, go to project settings and turn on advanced settings
7. Set Display -> Window -> Size -> Viewpoort (Width, Height) to (1920, 1080)
8. Set Window Override (Width, Height) to (1280, 720)
9. Set Display -> Window -> Stretch -> Mode to canvas_item
10. Rerun test, observe printed (150, 150) (unexpected)

**Minimal reproduction project:**
[set_mouse_pos Bug.zip](https://github.com/MikeSchulze/gdUnit4/files/11433568/set_mouse_pos.Bug.zip)

**Comment by Foxomat** [comment]
@MikeSchulze Okay I think I got it. Also added some code to make the test work.

**Comment by MikeSchulze** [comment]
@Foxomat i can't answer this question, as far as i know there is only one way to position the mouse.
Best you ask this question directly in the Godot forum or discord server
