### ISSUE TITLE
GD-18: Add C# support back

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#18]
**Describe What**
With GdUnit3 we had C# support and we want to have it with GdUnit4 too.

**Describe Why**
Requested by GdUnit3 users :)

**Dev hints**
needs to evaluate how c# is included in Godot4
- is there still a mono version + godot tools
- using the new GdExetension

**Comment by GeorgeS2019** [comment]
@MikeSchulze  there is NOW a [c# GdExetension](https://github.com/RhubarbVR/LibGodotSharp/issues/3#issue-1590923058)

**Comment by a2937** [comment]
Need any additional assistance in preparation for re-enabling C# support?

**Comment by MikeSchulze** [comment]
> Need any additional assistance in preparation for re-enabling C# support?

Any help is gladly appreciated ;)
I am in the final steps of releasing v4.1.1 and then would like to proceed with C# support.

It would be very helpful to convert the existing gd/csharp loader to GdExtention to address the [C# GdUnit library]( 
https://github.com/MikeSchulze/gdUnit4Mono)
I will create some tasks to organize the project.

Feel free to start with the GdExtention, I will assign the appropriate task to the PR later.

**Comment by MikeSchulze** [comment]
@a2937 I have started to revise the GdUnitMono project, but I have problems with it.
here is the actual PR https://github.com/MikeSchulze/gdUnit4Mono/pull/7

feel free to add suggestions

**Comment by PascalMarechal** [comment]
Hi guys,

Do we have any update on this feature?

Thanks :)

**Comment by a2937** [comment]
Unfortunately I have not had the time to work on this.

**Comment by aebersoft** [comment]
Hey just wanted to leave a note to say thank you for working on this (both the repo in general and this particular issue). No rush, but thank you :)
