### ISSUE TITLE
GD-19: Fix broken workflow `ci-pr` and switch to image bitbrain/godot-setup-action

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#19]
### Description
For GdUnit4 we use an alpha version of Godot4 where no image exists on `barichello/godot-ci`
We need to build your own image or dowload and install the Godot version manually

### Acceptance criteria
bring the workflow back in a succes state
https://github.com/bitbrain/godot-setup-action

**Comment by bitbrain** [comment]
@MikeSchulze in the interim, we can rely on custom built images for Godot 4 https://hub.docker.com/layers/zinefer/godot-ci/4/images/sha256-b03920d96fe97eb4b382f9a02ce8d02850970bbf3a363ce511f48719c7e25a68?context=explore

**Comment by MikeSchulze** [comment]
Thanks for that info. I will have a look to this at next week.
My plan was to build my own docker image.

**Comment by bitbrain** [comment]
@MikeSchulze after using said Docker image it comes with some problems (Godot throws some errors as it complains .NET is incorrectly setup). It may be better after all to build your own Docker image.
