### ISSUE TITLE
GD-213: Argument parsing hangs when test_parameters contains a string with mismatched brackets.

### ISSUE THREAD

**Issue by SdgGames** [MikeSchulze/gdUnit4#213]
**The used GdUnit4 version:**
4.1.1

**The used Godot version:**
v4.1.beta1.official [828ec2c5d]

**OS including version:**
Windows 11

**Describe the bug**
Unit tests will hang indefinitely if the test_parameters contains more closing brackets than opening brackets. I haven't 100% figured out what combination of tests will reproduce the result, but I have seen it multiple times while writing unit tests for a Mermaid parser.

In these test cases:
```
test_parameters := [
	["flowchart TD\nid[This is a standard node]"],
	["flowchart TD\nid(This is a node with rounded edges)"],
	["flowchart TD\nid([This is a stadium node])"],
	["flowchart TD\nid[[This is a box node]]"],
	["flowchart TD\nid[(This is a cylindrical node)]"],
	["flowchart TD\nid((This is a circular node))"],
	["flowchart TD\nid>This is a flag shaped node]"],
	["flowchart TD\nid{This is a rhombus node}"],
	["flowchart TD\nid{{This is a hexagon node}}"],
	["flowchart TD\nid[/This is a parallelogram node/]"],
	["flowchart TD\nid[\\This is also a parallelogram node\\]"],
	["flowchart TD\nid[/This is a trapezoid node\\]"],
	["flowchart TD\nid[\\This is also a trapezoid node/]"],
	["flowchart TD\nid(((This is a double circle node)))"]
```

the tests will hang with the following stack trace:
![image](https://github.com/MikeSchulze/gdUnit4/assets/83036002/0169ad99-c9ef-49e5-af06-af36b59d5611)
(sorry, I couldn't figure out how to copy text from the stack frame :) )

The line at fault is this one: 	`["flowchart TD\nid>This is a flag shaped node]"],`
I was able to get the tests to complete by moving this line to the very end of the array. I did some light debugging, and I see a lot of Regex, so my best guess is that it is reading the extra bracket as the end of the array element.

Interestingly, I can get it to fail with this test case:
```
test_parameters := [
	["flowchart TD\nid>This is a flag shaped node]"],
	["flowchart TD\nid(((This is a double circle node)))"],
```
but it passes with this test case:
```
test_parameters := [
	["flowchart TD\nid(((This is a double circle node)))"],
	["flowchart TD\nid>This is a flag shaped node]"],
```

**Steps to Reproduce**
Create a new unit test with multiple cases. One or more cases should contain a string with mismatched brackets.
```
	["flowchart TD\nid((This is a circular node))"],
	["flowchart TD\nid>This is a flag shaped node]"],
	["flowchart TD\nid{This is a rhombus node}"],
```

The closing bracket within the string in the center case will cause the parser to hang in the tokenization step.

I did try to reproduce the failure in a minimal way, but the minimal test cases would work just fine. Not sure why. Maybe length is a factor

**Minimal reproduction project:**
This function causes the hang. I removed the unit test contents since they are never reached.

```
## Tests every single node type. Reads, then writes the Mermaid string.
## Fails if the two graphs are not identical.
func test_parse_compose_node_types(chart: String, test_parameters := [
	["flowchart TD\nid[This is a standard node]"],
	["flowchart TD\nid(This is a node with rounded edges)"],
	["flowchart TD\nid([This is a stadium node])"],
	["flowchart TD\nid[[This is a box node]]"],
	["flowchart TD\nid[(This is a cylindrical node)]"],
	["flowchart TD\nid((This is a circular node))"],
	["flowchart TD\nid>This is a flag shaped node]"],
	["flowchart TD\nid{This is a rhombus node}"],
	["flowchart TD\nid{{This is a hexagon node}}"],
	["flowchart TD\nid[/This is a parallelogram node/]"],
	["flowchart TD\nid[\\This is also a parallelogram node\\]"],
	["flowchart TD\nid[/This is a trapezoid node\\]"],
	["flowchart TD\nid[\\This is also a trapezoid node/]"],
	["flowchart TD\nid(((This is a double circle node)))"]
]) -> void:
	pass

```

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug.
