### ISSUE TITLE
Godot editor can not be closed

### ISSUE THREAD

**Issue by Krigu** [MikeSchulze/gdUnit4#225]
### The used GdUnit4 version:
gdUnit4 4.1.2

### The used Godot version:
Godot 4.1

### OS including version:
Manjaro Linux 

### Describe the bug
We are using GdUnit in our build pipeline and after updating to Godot 4.1 the build does not finish, because after sucessfully executing the tests (in headless mode) the build gets stuck. We are running the tests with the following command:

`./addons/gdUnit4/runtest.sh -a tests/gdunit/ -c`

### Steps to Reproduce

I was able to reproduce the error without the command line tools in a clean project.

- Started godot via command line
- Created a new project in Godot 4.1
- Added gdUnit Plugin 4.1.2
- Reloaded project
=> The terminal is showing "Unload GdUnit4 Plugin success", but then it hangs and the process does not get terminated. 

Hope this helps to find the bugs. If you need more information please let me know. Thanks for gdUnit btw., we really appreciate it

**Comment by MikeSchulze** [comment]
I current working on running GdUnit4 on Godot 4.1, but looks like Godot 4.1 itself has some issues.
https://github.com/MikeSchulze/gdUnit4/issues/224

**Comment by MikeSchulze** [comment]
It is a Godot crash issue, the plugin is unloading successfully.
There a many issues about crashing for release 4.1
```
----------------------------------------------------------------
Cleanup singletons ["GdUnitCommandHandler", "GdUnitAsserts"]

	Unregister singleton 'GdUnitCommandHandler'
	Free singeleton instance 'GdUnitCommandHandler:<RefCounted#-9223369276700690972>'
	Succesfully freed 'GdUnitCommandHandler'

	Unregister singleton 'GdUnitAsserts'
	Free singeleton instance 'GdUnitAsserts:[]'
	Succesfully freed 'GdUnitAsserts'
----------------------------------------------------------------
Unload GdUnit4 Plugin success
EditorSettings: Save OK!
```

**Comment by MikeSchulze** [comment]
I tested around and removed class by class and finally ended up in a empty plugin, but it crashs too.
Finally i create a new project and build a new plugin over the Godot tools.
Godot crashes just by adding the print statement ..., i will open a Godot issue, and close this issue as Godot releated
```
@tool
extends EditorPlugin


func _enter_tree():
	# Initialization of the plugin goes here.
	pass


func _exit_tree():
	prints("_exit_tree")
	# Clean-up of the plugin goes here.
	pass
```

**Comment by Krigu** [comment]
Thank you for adressing it so quickly.

I fixed it temporarly by removing the line `prints("Unload GdUnit4 Plugin success")` in the file `plugin.gd`.
