### ISSUE TITLE
Signals not emitting in test suite

### ISSUE THREAD

**Issue by TheWalruzz** [MikeSchulze/gdUnit4#226]
**The used GdUnit4 version:**
4.1.2

**The used Godot version:**
4.1

**OS including version:**
Windows 11

**Describe the bug**
While trying to write tests for my signal extensions library, I noticed that emissions for signals defined in a test suite do not work - the connected Callable is not called at all. 
I created the simplest possible test case (as shown below) without using my library and the issue was still present. 
I also tried waiting a little bit before the final assertion, but the callback still didn't fire and the test failed.

**Steps to Reproduce**
1. Create a simple test suite:
```gdscript
extends GdUnitTestSuite


signal some_signal()


func test_signals() -> void:
	var result := false
	some_signal.connect(func(): result = true)
	some_signal.emit()
	assert_bool(result).is_true()
```
2. Run the test
3. The test fails

**Minimal reproduction project:**
Shown above

**Comment by MikeSchulze** [comment]
This is not a GdUnit bug. 

You can test by your self by creating a scene and attache this script

```gdscript
extends Node

signal some_signal()

func _ready():
	test_signals()


func test_signals() -> void:
	var result := false
	some_signal.connect(func():
		result = true
		prints("some_signal emitted", result)
	)
	some_signal.emit()
	await get_tree().process_frame
	prints("test", result)
```

```shell
some_signal emitted true
test false
```

Please create an issue about this on Godot https://github.com/godotengine/godot/issues/new/choose

I am not sure that it is expected/allowed to change an external variable in a callable.

Close as not GdUnit4 related
