### ISSUE TITLE
GD-256: Orphan node detection is incorrect, add_child and auto_free results in orphan nodes

### ISSUE THREAD

**Issue by pennyloafers** [MikeSchulze/gdUnit4#256]
**The used GdUnit4 version:**
4.1.1

**The used Godot version:**
standard 4.1.1

**OS including version:**
Ubuntu, intel integrated gpu

**Describe the bug**
Auto free object added as child to tree is orphaned created during before and before_test

**Steps to Reproduce**
1. Run testsuite in editor

**Minimal reproduction project:**
```
class_name MyTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')


var before_node
var before_test_node

func before():
	before_node = auto_free(Node.new())

func before_test():
	before_test_node = auto_free(Node.new())

func test_auto_free_before_test() -> void:
	# test case orphan warning
	add_child(before_test_node)

func test_auto_free_before() -> void:
	# test suite orphan warning
	add_child(before_node)

func test_auto_free_local() -> void:
	# works fine
	var local_test_node = auto_free(Node.new())
	add_child(local_test_node)

```

![image](https://github.com/MikeSchulze/gdUnit4/assets/33847042/093dd43b-d9e6-493b-8581-a631d63bafd7)

**Comment by pennyloafers** [comment]
I think the same orphan issue happens for spies and mocks as well if they are created in the before_test phase.

**Comment by MikeSchulze** [comment]
Thanks for reporting, I will have a look at it in the evening.

**Comment by MikeSchulze** [comment]
yes there is definitely a bug in there, i will rewrite the recognize from orphan noded to the individual stages, i was never really happy with the current implementation

**Comment by MikeSchulze** [comment]
While debugging this scenario, I see that your test setup is wrong.

You create a node at the **before()** and stage **before_test()**, but you don't add it to the test until later.
This is simply wrong!

The **before_test()** stage is called for every test, so the node you create is available in every test.
It doesn't make sense to add the child only in a particular test, you have to add it in the **before_test()** stage where it was created.

### Correct version
```
class_name MyTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')


var before_node
var before_test_node

func before():
	before_node = auto_free(Node.new())
        add_child(before_node)


func before_test():
	before_test_node = auto_free(Node.new())
        add_child(before_test_node)


func test_auto_free_before_test() -> void:
	prints(before_test_node)


func test_auto_free_before() -> void:
	prints(before_node)
	

func test_auto_free_local() -> void:
	var local_test_node = auto_free(Node.new())
	add_child(local_test_node)
```

Unfortunately, I cannot extend the orphan node detection to catch such cases, there is simply no possibility to do so in Godot. Godot is unfortunately very simple, I can only determine the current orphan count at a certain point in time. If there were a function to get the list of existing orphan nodes, I could hold them up, but that's not how it works.

**Comment by pennyloafers** [comment]
Fair enough. I think a warning the auto_free requires the node to be added to the tree in the same code block to avoid orphaning the node would be nice.

**Comment by MikeSchulze** [comment]
> Fair enough. Can a warning the auto_free requires the node to be added to the tree in the same code block to avoid orphaning the node?

I can't add a warning by default, it depends on what you want to test.
It is not always necessary to add a node to the tree if, for example, you only want to test functions that do not require the node to have a parent.
