### ISSUE TITLE
GD-259: Run overall command does not take into account Test Root Folder

### ISSUE THREAD

**Issue by hberten** [MikeSchulze/gdUnit4#259]
**The used GdUnit4 version:**
4.1.4

**The used Godot version:**
4.1.1.stable

**Describe the bug**
The run overall command does not take into account changes to the "Test Root Folder" option. I believe this stems from [this line](https://github.com/MikeSchulze/gdUnit4/blob/976d9087463c4f8a82c2dccbf5b907cc9e8235b3/addons/gdUnit4/src/core/command/GdUnitCommandHandler.gd#L270), which I assume should include GdUnitSettings.test_root_folder() rather than just "test".

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug.
