### ISSUE TITLE
Monitor Signals not working

### ISSUE THREAD

**Issue by gumaciel** [MikeSchulze/gdUnit4#273]
**The used GdUnit4 version:**
4.1.4

**The used Godot version:**
4.1.2

**OS including version:**
MacOS

**Describe the bug**
This code is always true

```gdscript
class MyEmitter extends Node:
	signal my_signal_a
	signal my_signal_b(value :String)
	func do_emit_a() -> void:
		my_signal_a.emit()
		
	func do_emit_b() -> void:
		my_signal_b.emit("foo")
	
func test_signal() -> void:
	var my_emitter := monitor_signals(MyEmitter.new())

	assert_signal(my_emitter).wait_until(10).is_emitted("my_signal_a")

```

**Steps to Reproduce**
- Create a script with the code above

**Comment by gumaciel** [comment]
Also: As I can see, there's no way to test a Global Script Signal if the signal is emitted twice because gets an error:

`Error: 'Invalid type in function 'monitor_signals' in base 'Node (Globals)'. The Object-derived class of argument 1 (previously freed) is not a subclass of the expected argument class.'`

**Comment by MikeSchulze** [comment]
hi @gumaciel have you read the documentation ?
https://mikeschulze.github.io/gdUnit4/asserts/assert-signal/

check the examples e.g.
https://mikeschulze.github.io/gdUnit4/asserts/assert-signal/#wait_until

`await assert_signal(instance).wait_until(5000).is_emitted("door_closed")`

You have forgot to use the `await` in your test.

```
func test_signal() -> void:
	var my_emitter := monitor_signals(MyEmitter.new())

	await assert_signal(my_emitter).wait_until(10).is_emitted("my_signal_a")
```

**Comment by MikeSchulze** [comment]
> Also: As I can see, there's no way to test a Global Script Signal if the signal is emitted twice (two test methods) because gets an error:
> 
> `Error: 'Invalid type in function 'monitor_signals' in base 'Node (Globals)'. The Object-derived class of argument 1 (previously freed) is not a subclass of the expected argument class.'`

You want to spy on a global script, which is technically impossible.
Global scripts are singletons, i.e. there is only one instance, which is held by the engine.
