### ISSUE TITLE
GD-278: GdUnit Inspector: Test marks as passed if both warning and error 

### ISSUE THREAD

**Issue by JonBoyleCoding** [MikeSchulze/gdUnit4#278]
**The used GdUnit4 version:**
4.1.4 

**The used Godot version:**
 v4.1.1.stable.nixpkgs.bd6af8e0e

**OS including version:**
NixOS 23.04 - Nvidia RTX GPU

**Describe the bug**

If a warning is emitted during the test (e.g. orphaned nodes) the overall test is marked as a success with warning regardless of it it is or not.

The failures icon states a failure, but the green tick next to the test suggests a pass despite that it should be failing.

![image](https://github.com/MikeSchulze/gdUnit4/assets/630329/e6048cec-165b-4f56-93d1-be59c0ff8d52)

I would expect something more like...

![image](https://github.com/MikeSchulze/gdUnit4/assets/630329/d1e53697-df6c-469f-bbb5-a933c753b3c1)

As an aside - I would prefer also to have the overall count be a failure rate rather than a success rate - or at least have it be (pass/warning/fail/errors) rather than combining warning/fail. Is there a way to do this - or perhaps should I make a separate request for this?

**Steps to Reproduce**

Run the test in the minimal reproduction section.

**Minimal reproduction project:**

```
class_name MyTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')


var before_node

func before_test():
	before_node = Node.new()

func test_one():
	assert_bool(true).is_true()
	
func test_two():
	assert_bool(true).is_false()
```

**Comment by MikeSchulze** [comment]
@justin-calleja you need to use `monitor_signals`, the assert_signal does only catch signals at the assertion time.

https://godot-gdunit-labs.github.io/gdUnit4/latest/advanced_testing/signals/#monitor-signals
