### ISSUE TITLE
GD-283: Rename Result class to GdUnitResult

### ISSUE THREAD

**Issue by imberny** [MikeSchulze/gdUnit4#283]
I want to use this, but the Result type conflicts with [Godot-Optional](https://github.com/WhoStoleMyCoffee/godot-optional)'s own Result type, forcing me to either abandon one or modify one to resolve the conflict.

Result is *almost* the only type not to be prefixed with GdUnit. It is a common programming concept and therefore prone to clash with other addons or the user's own code. It is frustrating that a type from a unit testing addon would interfere with my production code.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue, yes the class should be prefixed to prevent conflicts.
