### ISSUE TITLE
Add delete .godot folder note to documentation

### ISSUE THREAD

**Issue by andrew-wilkes** [MikeSchulze/gdUnit4#290]
I found that I needed to delete the .godot folder when upgrading to v4.2 in order for this AddOn to work. So, please add a note regarding this to the documentation.

**Comment by MikeSchulze** [comment]
Hi, this is a Godot related issue and should be reported [here](https://github.com/godotengine/godot/issues)
Just deleting the .godot folder has some side effects and I don't want to suggest it.
e.g. when you delete the .godot folder will result into issues with scenes and resource loading.
The caching stuff on Godot has a lot of problems, seems to be the latest version 4.2 has introduced new caching bugs.

So please report this issue on Godot.
