### ISSUE TITLE
assert_runtime request

### ISSUE THREAD

**Issue by Starkandco** [MikeSchulze/gdUnit4#294]
**Is your feature request related to a problem? Please describe.**
I would like to easily be able to put an assert at the end of each test which would cause failure if the entire unit test in question has exceeded some specified time.

**Describe the solution you'd like**
Ideally a new func, maybe it could be something like assert_runtime(~~self~~).is_less_than(some_ms_value e.g. 1000) which would also allow the inverse of .is_more_than(some_ms_value) which could be used to ensure that something that should take time is taking the expected amount of time to run. I'm not sure how valuable an is_equal would be here.

**Describe alternatives you've considered**
It is straightforward to count the milliseconds of a unit test by taking the start and end time and use existing asserts for this purpose.

**Comment by Starkandco** [comment]
//aside really impressed with the solution sorry if there's something like this already :)

**Comment by MikeSchulze** [comment]
Hi, this is already possible by using the test-case timeout argument.
See here  [testcase timeout](https://mikeschulze.github.io/gdUnit4/faq/test-case/#timeout)

You only need to add this argument to your test. Check the documentation for additional details like default timeout.
