### ISSUE TITLE
GD-299: `assert_str()` reports error when using `StringName`

### ISSUE THREAD

**Issue by VagabondOfHell** [MikeSchulze/gdUnit4#299]
**The used GdUnit4 version:**
4.2.0

**The used Godot version:**
4.1.3

**OS including version:**
Windows 11

**Describe the bug**
When passing a StringName to assert_str, an error of `GdUnitStringAssert inital error, unexpected type <StringName>` is reported

**Steps to Reproduce**
Run the following test file:
```
# GdUnit generated TestSuite
class_name ReproductionTests
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')

# TestSuite generated from
const __source = 'res://core/extensions/node_extensions.gd'

const NODE_NAME = "sample"
var node;

func before_test():
	node = CharacterBody3D.new()
	node.name = NODE_NAME

	auto_free(node)

func test_node_name_assert_str():
	assert_str(node.name).is_equal(NODE_NAME)

```

**Solution**:
Inside GdUnitStringAssertImpl._init extend the if statement to include TYPE_STRING_NAME
```
if not _base.__validate_value_type(current, TYPE_STRING) and not _base.__validate_value_type(current, TYPE_STRING_NAME):
		report_error("GdUnitStringAssert inital error, unexpected type <%s>" % GdObjects.typeof_as_string(current))
```

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.

`assert_str` was originally built for testing against `String`, with Godot 4.x `StringName` was introduced and should of course also be handled.
