### ISSUE TITLE
GD-303: `Script_Error` settings should not report script errors when is caught by an `assert_error`

### ISSUE THREAD

**Issue by VagabondOfHell** [MikeSchulze/gdUnit4#303]
**The used GdUnit4 version:**
4.2.0

**The used Godot version:**
4.1.3

**OS including version:**
Windows 11

**Describe the bug**
A Godot Runtime Error is thrown when using assert_error().is_runtime_error, preventing the test from succeeding. If the configuration option for Godot.Script Error is disabled then the test succeeds as expected

**Steps to Reproduce**
Run the below test with the configuration setting Godot.Script Error enabled

```
# GdUnit generated TestSuite
class_name AssertExtensionsTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')

# TestSuite generated from
const __source = 'res://core/extensions/assert_extensions.gd'

func do_a_fail():
	assert(3 == 1, 'test')

func test_assert_method() -> void:	
	await assert_error(do_a_fail).is_runtime_error('Assertion failed: test')
```

![image](https://github.com/MikeSchulze/gdUnit4/assets/3276362/94692977-5c5b-4433-8497-ce0c01ac716a)

![image](https://github.com/MikeSchulze/gdUnit4/assets/3276362/380356ab-89f3-49d4-b28f-a35f47572752)

![image](https://github.com/MikeSchulze/gdUnit4/assets/3276362/f2e6d5aa-b05b-4874-9515-89589a48f522)
![image](https://github.com/MikeSchulze/gdUnit4/assets/3276362/6233a208-260e-4782-bdb8-510ceb9379e0)

**Expected Result**
Test should succeed if the message is expected by an is_runtime_error call

**Comment by MikeSchulze** [comment]
Hi, the `assert_error` works as expected in "run" mode, when using "debug mode" the Godot debugger stops at the `assert_error`.
To understand the mechanics behind, you should know, Godot has no exception or error reporting handler.
Using  `assert_error` scans the Godot log for error entry to be reported.
On "Debug" mode, it writes an entry into 
```
USER SCRIPT ERROR: Assertion failed: test
   at: GdUnitGodotErrorAssertImplTest.do_a_fail (res://addons/gdUnit4/test/asserts/GdUnitGodotErrorAssertImplTest.gd:137)
```
On "Run" mode, Godot do not report anything is just stops at `assert(3 == 1, 'test')`.

**So you can say that it is a Godot issue, as no errors are written to the log in debug mode.**


And the configuration setting Godot.Script Error enabled/disable is not related to the `assert_error`!
It is just an enabler to check during runtime for script errors if enabled and report it as a failure.

**Comment by VagabondOfHell** [comment]
Hi @MikeSchulze 

Was this response meant for https://github.com/MikeSchulze/gdUnit4/issues/304? This issue is related to the test failing if the config entry isn't disabled. Issue 304 is for the debug vs run mode, which your response makes sense for and is in line with what I had found before making the issue.

**Comment by MikeSchulze** [comment]
Hi @VagabondOfHell, both issues describe the same problem of `assert_error` in "Debug" vs "non Debug" mode.

I haven't seen the other issue https://github.com/MikeSchulze/gdUnit4/issues/304 before I answered this issue.

About the `Godot.Script Error enabled/disable`  from the [documentation](https://mikeschulze.github.io/gdUnit4/first_steps/settings/)
```
Script Error
This setting reports Godot gdscript errors in GdUnit and causes the associated test to fail. 
When Godot encounters an error in a gdscript file, such as a syntax error or a runtime error, GdUnit can capture the error and cause the associated test to fail. 
By enabling this setting, you can ensure that errors in gdscript files are detected and reported in your tests.
```

**Comment by VagabondOfHell** [comment]
@MikeSchulze 
This error has nothing to do with debug mode though. In the screenshots above I used run mode for both.

If you have that configuration option enabled and run the test in run mode, it is reported as an error and the test fails. But it shouldn't fail when I am testing against the assert directly. I would expect that option should fail tests that assert when it isn't being tested for.

The test shouldn't fail when an assert is reported if the success condition is that an assert was reported.

**Comment by MikeSchulze** [comment]
Hi @VagabondOfHell, 
I think there is a misunderstanding of the GdUnit4 settings.

![image](https://github.com/MikeSchulze/gdUnit4/assets/347037/c16ce709-30a1-4c43-a922-6bc03b3add6e)


This setting activates/deactivates a general option for reporting script errors, and works independently of the use of `assert_error`.
This means that if you execute scripts in a **GdUnit** test context and this contains script errors, these are reported by default if this option is activated.

You can verify it by simply run this test
```
func do_a_fail():
	assert(3 == 1, 'test')

func test_assert_method() -> void:
	do_a_fail()
```
This option is a kind of all-round check that can be activated if desired to report errors when testing the script.
However, if you want to test explicitly for errors, you should deactivate this option and test with `assert_error`.

If there are any uncertainties or requests for improvement, please let me know.

I am open to any kind of improvement wishes, thank you very much and a happy new year

**Comment by VagabondOfHell** [comment]
Yeah, I understand all of that. I just think that it works against the purpose of the test. The configuration value shouldn't determine if the test passes or fails.

If we set the configuration value to true:

When using your sample code above
```
func do_a_fail():
	assert(3 == 1, 'test')

func test_assert_method() -> void:
	do_a_fail()
```

This should fail the test (like it does). An assertion was thrown that the test wasn't expecting to handle.

When using my sample code in the original post
```
func do_a_fail():
	assert(3 == 1, 'test')

func test_assert_method() -> void:	
	await assert_error(do_a_fail).is_runtime_error('Assertion failed: test')
```
This should not fail the test (like it does). The test was expecting this assertion, so the test should be marked as success.

With the configuration value set to true, it is impossible for the is_runtime_error to pass the test.

Whether this is an improvement or a bug I'll leave it to you to decide, but right now that config value prevents the is_runtime_error assertion from marking the test as Passed.

Thank you for the great add-on, and have a happy new year yourself

**Comment by MikeSchulze** [comment]
Ok, that's a good point.

I can improve the general script error reporting by respect the error was already caught by a `assert_error`, yes that makes sense.

**Comment by MikeSchulze** [comment]
fixed
