### ISSUE TITLE
GD-304: is_runtime_error does not find assertion in debug mode

### ISSUE THREAD

**Issue by VagabondOfHell** [MikeSchulze/gdUnit4#304]
**The used GdUnit4 version:**
4.2.0

**The used Godot version:**
4.1.3

**OS including version:**
Windows 11

**Describe the bug**
Assertions fail to be caught/are not found by the monitor when running the tests in Debug mode

**Steps to Reproduce**
Run the following Test in Debug Mode
```
# GdUnit generated TestSuite
class_name AssertExtensionsTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')

# TestSuite generated from
const __source = 'res://core/extensions/assert_extensions.gd'

func do_a_fail():
	assert(3 == 1, 'test')

func test_assert_method() -> void:	
	await assert_error(do_a_fail).is_runtime_error('Assertion failed: test')
```

Running normally:
![image](https://github.com/MikeSchulze/gdUnit4/assets/3276362/40d5b9f4-9130-4bc4-8949-0c86929cab64)

Running in debug mode:
![image](https://github.com/MikeSchulze/gdUnit4/assets/3276362/22d883f1-aa24-402c-a3ef-5bf122ad7a9a)

**Comment by MikeSchulze** [comment]
see https://github.com/MikeSchulze/gdUnit4/issues/303#issuecomment-1872518747

**Comment by MikeSchulze** [comment]
Unfortunately there is nothing I can do here, as long as Godot himself does not 
writes an error in the log or offers an error handler, my hands are tied here.

I am therefore closing this topic as clarified.

**Comment by brianrodri** [comment]
Hmm is there a function we can use to detect this GdUnit4's "debug mode"? `OS.is_debug_build()` returns true for both modes, and I'm not sure what I can use in its place.
