### ISSUE TITLE
GD-307: Add possibility to use argument matcher when asserting signals

### ISSUE THREAD

**Issue by Krigu** [MikeSchulze/gdUnit4#307]
**Is your feature request related to a problem? Please describe.**
Currently there is no possibility no way to use the existing argument matchers when asserting if a signal got sent. So you have to know the type and the specific value of the argument to write the assertion.

**Describe the solution you'd like**
It would be great to check if a signal gets emitted of a certain type with the existing argument matchers:

`assert_signal(test_class).is_emitted("SIGNAL_NAME", [any_string()])`

**Comment by MikeSchulze** [comment]
Hi @Krigu

I'm not sure if that really makes sense.
Why would you test for a signal and ignore the arguments?
You want to make sure that a certain signal is sent with the expected parameters.

Can you please specify the use case in more detail?

**Comment by voithos** [comment]
For what it's worth, I'd also like this feature. In my opinion, it's useful for the same reason that function argument matchers are useful: sometimes a test isn't concerned with the specific values of a function call, and is "just" testing the behavior that the function is called under certain conditions. (And then typically you'd have separate test cases that can test specific values)

This is the same idea, just in the context of signals.

As a data point, when I was writing some signal tests recently, I just expected the matchers to work and was surprised when they didn't.

**Comment by MikeSchulze** [comment]
Hello, the argument matchers were originally only intended for the mock verify functions.
But yes I understand what you mean and yes that makes perfect sense.
