### ISSUE TITLE
push_error() should be captured when it occurs in an assert_error() lambda

### ISSUE THREAD

**Issue by voithos** [MikeSchulze/gdUnit4#309]
**Is your feature request related to a problem? Please describe.**
When using `assert_error` along with `is_push_error`, the error shows up in Godot's error list when running tests. This is a bit confusing, and may potentially mask other, actual error that occur during the tests. Enabling "report of push_error as failure" doesn't work as a workaround, as that makes even expected errors (`is_push_error`) cause failures.

**Describe the solution you'd like**
Ideally `push_error` would not show up as an actual error when called in the context of an `assert_error` lambda.

I'm not sure how hard this is to do or it's even possible with Godot currently (can `push_error` be temporarily overridden with a custom implementation?), but wanted to file the feature request regardless.

**Describe alternatives you've considered**
There's no real workaround as far as I know, but it's not the biggest problem so at the moment it just requires more careful manual inspection of the errors list after running tests.

**Additional context**
N/A

**Comment by MikeSchulze** [comment]
This is already fixed in V4.2.1.
Close as duplicate to #303

**Comment by voithos** [comment]
Oh thanks!

**Comment by MikeSchulze** [comment]
No problem, feedback and improvements always welcome.

**Comment by voithos** [comment]
I updated my project to the latest gdUnit4 master, and one small thing I noticed is that the error seems to still go uncaptured when running the "Run overall tests" command, but it will correctly capture if you just run the unit test directly. I don't exactly know the difference between the two run modes beyond which tests they have selected, but this seemed a bit surprising (although it's easy to work around).

**Comment by MikeSchulze** [comment]
> I updated my project to the latest gdUnit4 master, and one small thing I noticed is that the error seems to still go uncaptured when running the "Run overall tests" command, but it will correctly capture if you just run the unit test directly. I don't exactly know the difference between the two run modes beyond which tests they have selected, but this seemed a bit surprising (although it's easy to work around).

Hi @voithos, that sounds like an error. The test results should be the same regardless of how you perform the tests.
Please create a new bug issue, and add steps to reproduce.
