### ISSUE TITLE
Scene Runner hangs the test if the scene loads a new scene

### ISSUE THREAD

**Issue by dreed-sd** [MikeSchulze/gdUnit4#311]
**The used GdUnit4 version:**
4.2.1

**The used Godot version:**
4.2 stable

**OS including version:**
Mac M1

**Describe the bug**
Using a SceneRunner to load a scene whose code loads a new scene, causes the test to hang and never complete until aborted. It would be useful if a runner could support this, so you can write integration tests that span multiple scenes. In my case for example I want to test that a bootstrap scene successfully loads a second scene when it is done bootstrapping. 

**Steps to Reproduce**

```
# define a test like this
func test_loads_main_scene() -> void:
    var runner := scene_runner("res://bootstrap.tscn")

# bootstrap should have a node whose script performs the following:
get_tree().change_scene_to_file("res://some_other_scene.tscn")
```

When you run the test it will spin forever and never complete.

**Comment by MikeSchulze** [comment]
Hi @dreed-sd

This test scenario is not actually possible.
The GdUnit4 Test Runner is itself a scene and is executed as a user-defined scene with `play_custom_scene()` or as the main scene in debug mode.

When you're changing the actual running scene, you will break the running `TestRunner` scene.
Godot can only run one active main scene and makes this scenario impossible.

Therefore, test whether your bootstrapping is working properly by mocking it and using verify to check whether the desired scene has been changed.

Your bootstrap should provide a function you can mock to not call the real implementation.
At least, you only want to test that your bootstrap is switching the scenes to a scene named xyz.

```
func change_scene_to_file(scene :String) -> bool:
	get_tree().change_scene_to_file(scene)
	return true
```

And your test should look like this.
```
func test_bootstarp_scene() -> void:
	var mock_bootstrap = mock("res://bootstrap.gd", CALL_REAL_FUNC)
	
	# do overwrite the `change_scene_to_file` to not call the real implementation
	do_return(true).on(mock_bootstrap).change_scene_to_file(any_string())
	add_child(mock_bootstrap)
	
	# is initial called
	verify(mock_bootstrap, 1)._ready()
	
	# await a bit more as 2s to verify its switched the scene
	await await_millis(2500)
	verify(mock_bootstrap, 1).change_scene_to_file("res://some_other_scene.tscn")
```
