### ISSUE TITLE
GD-320: An expected `push_error()` is not silenced when running via "Run overall tests"

### ISSUE THREAD

**Issue by voithos** [MikeSchulze/gdUnit4#320]
**The used GdUnit4 version:**
Latest master

**The used Godot version:**
4.2.1

**OS including version:**
Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.2849) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

**Describe the bug**
This seems related to #309.

When running a test that checks for an expected `push_error()`, the error is normally silenced when running an individual test. However, if you run a whole project's suite using the "Run overall tests" button, the error is incorrectly output to Godot's errors console.

**Steps to Reproduce**
1. Create a function that emits `push_error()`
2. Create a test that runs that function using `await assert_error()` and checks for the push error
3. Click "Run overall tests" and observe that the test passes, but the error message is still emitted to Godot's console

**Minimal reproduction project:**
[bug-repro.zip](https://github.com/MikeSchulze/gdUnit4/files/13945665/bug-repro.zip) (includes latest gdUnit4 in the addon directory)

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug, I will take a look into in the evening.

**Comment by MikeSchulze** [comment]
After a short test i can't reproduce, the console shows no error.
![image](https://github.com/MikeSchulze/gdUnit4/assets/347037/11d5545d-7a49-46f1-bcdd-f9254fb07672)

**Comment by voithos** [comment]
Ah I didn't mean the gdUnitConsole, but rather Godot's `Debugger` tab: 
![image](https://github.com/MikeSchulze/gdUnit4/assets/744228/f9f572cd-d810-4697-bde3-442c49b52148)

I just noticed it also seems to trigger when running the test with "Rerun unit tests (Debug)", so it seems like it may be a debug-mode related thing.
![image](https://github.com/MikeSchulze/gdUnit4/assets/744228/fa1ec7b3-1852-444f-aede-60450513148c)

When running using the normal "Rerun unit tests" button, there are no errors emitted:
![image](https://github.com/MikeSchulze/gdUnit4/assets/744228/3ae71c41-a58b-4794-ae83-13583982f880)

**Comment by MikeSchulze** [comment]
Hi, that's not a GdUnit4 bug.
A `push_error`or `push_warning` are generally collected by the Editor when running in Debug mode, there is nothing I can do.
Godot has no error handler to interact, so I have no control over this editor part.

**Comment by voithos** [comment]
I see, well I'm not sure how much effort it would be but it might be nice to see if Godot could add a proper error handler in future versions specifically so that testing libraries like GdUnit4 can control the engine's behavior during test execution in the future. At the end of the day, the tests are running in the editor so it's a bit odd that the editor reports errors when there are none.

But this isn't a big deal and is easy to just keep in mind as a user (a lower-cost improvement would be to add a short documentation notice about this around `assert_error` or something).

Just offering some optional suggestions, feel free to keep this closed. :)

**Comment by MikeSchulze** [comment]
Unfortunately, nothing will change on Godot's part - I already mentioned this a good 2 years ago.
I guess this is not needed to extra document, `push_error` is well documented in the Engine.
