### ISSUE TITLE
GD-323: SceneRunner `simulate_mouse_move_relative` speed is not functioning correctly

### ISSUE THREAD

**Issue by dreed-sd** [MikeSchulze/gdUnit4#323]
**The used GdUnit4 version:**
4.2.1

**The used Godot version:**
4.2 stable

**OS including version:**
Mac M1, OSX

**Describe the bug**
The speed of the movement is not as [documented](https://mikeschulze.github.io/gdUnit4/advanced_testing/sceneRunner/#simulate_mouse_move_relative), and can run forever.

```
runner.simulate_mouse_move_relative(Vector2(100, 0), Vector2(1, 1))
```

According to the docs, the default speed is 1 pixel per second. So giving `Vector(2, 2)` for example should move the cursor twice as fast. However, what it actually does is divide the movements up into 10 desecrate movements, and waits for Speed/10 _seconds_ between each. It looks like it expects `create_timer` to accept milliseconds, but works in [seconds](https://docs.godotengine.org/en/stable/classes/class_scenetree.html#class-scenetree-method-create-timer). That means a Speed of 2 is actually going to take 2 seconds, and a Speed of 3, 3 seconds, and so on, so it gets slower with higher speeds. This default behavior of 10 iterations also means the movement is very jerky -- the higher the speed the more jerky it is. And finally, giving it a fast speed will cause it to overshoot the destination, and then the `is_equal_approx(final_pos)` check fails, and the movement continues forever. I suggest a 3rd optional parameter to specify the 'resolution' of the movement, so you can decide how smooth the movement is.

**Comment by MikeSchulze** [comment]
Hi @dreed-sd thanks for reporting this issue.

Yes, I have to agree with you, the movement is quite bumpy. The suggestion to specify a resolution is very useful, I think there should also be an acceleration value to better simulate human mouse movements (like starting fast and stopping slow).

**Comment by dreed-sd** [comment]
That's a great API, I like the addition of `simulate_mouse_move_absolute` too, that will be easier for my use case. Thanks for the lightning fast fix! I am enjoying writing tests with GdUnit!
