### ISSUE TITLE
GD-348: Reports still reference gdUnit3 instead of gdUnit4

### ISSUE THREAD

**Issue by Eggbertx** [MikeSchulze/gdUnit4#348]
### The used GdUnit4 version

4.2.1 (Pre Release/Master branch)

### The used Godot version

v4.2.1.stable.arch_linux

### Operating System

Arch Linux

### Describe the bug

Although it is not immediately obvious by doing a search via something like `grep -rni gdunit3`, some reports still reference gdUnit3 when rendered. There are also some spelling errors (e.g., "Comming" instead of "Coming".

### Steps to Reproduce

1. Run `GODOT_BIN=godot ./addons/gdUnit4/runtest.sh -a ./test/` from the project root
2. Open the generated report

**Comment by Eggbertx** [comment]
I created a pull request that addresses this: #349

**Comment by MikeSchulze** [comment]
Thanks for the findings ;)
