### ISSUE TITLE
GD-353: Right click context menu popup at wrong position 

### ISSUE THREAD

**Issue by jinsediaoying** [MikeSchulze/gdUnit4#353]
### The used GdUnit4 version

4.2.1 (Pre Release/Master branch)

### The used Godot version

v4.2.1 stable

### Operating System

win 11, with 4 screens
![image](https://github.com/MikeSchulze/gdUnit4/assets/25916527/68f4277a-fe15-4f5f-b32e-ba36355a0614)

### Describe the bug

![image](https://github.com/MikeSchulze/gdUnit4/assets/25916527/280455c8-1687-4a9b-879b-f5c94ca7a3b7)
The test case right click context menu popup at wrong position, maybe becasue I have multiple screens.

### Steps to Reproduce

right click on a test case

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.
