### ISSUE TITLE
GD-359: Support dynamic test parameter resolving

### ISSUE THREAD

**Issue by Vacui** [MikeSchulze/gdUnit4#359]
**Is your feature request related to a problem? Please describe.**
Nope, just an inconvenience 👍 

**Describe the solution you'd like**
Support for objects of type `Callable` as parameters in a parameterized test.

**Describe alternatives you've considered**
The currently suggested and implemented alternative is to duplicate the test, grouping common code in util functions if necessary.

**Additional context**
A simplified version of the test I am trying to convert from my old GUT implementation to the new GdUnit4:
```
extends GutTest

var rng: RandomNumberGenerator
var mock_game_service: GameService
var player_unit: Unit

func before_all():
	rng = RandomNumberGenerator.new()

func before_each():
	var resources_manager_service = ResourcesManagerService.new()
	resources_manager_service.setup("res://src/test")
	Services.register(resources_manager_service)

	var waves_service = WavesService.new()
	Services.register(waves_service)
	mock_game_service = partial_double(GameService).new()
	Services.register(mock_game_service)

	mock_game_service.start_game(load("res://src/test/test_game_mode.tres") as GameMode)
	waves_service.next_phase()

	player_unit = mock_game_service.get_state().player_board.get_all_values()[0]

func after_each():
	Services.remove_all()


var evaluate_condition_params = ParameterFactory.named_parameters(
	["test", "get_unit", "get_rng", "expected_res"],
	[
		["fail condition if unit is not valid", func(): return null, func(): return rng, false],
		[
			"fail condition if rng is not valid",
			func(): return player_unit,
			func(): return null,
			false
		],
		[
			"fail condition if unit is not in the board",
			func(): return Unit.new("test_player_unit", rng),
			func(): return rng,
			false
		],
		[
			"pass condition if parameters are valid",
			func(): return player_unit,
			func(): return rng,
			true
		]
	]
)

func test_evaluate_condition(params = use_parameters(evaluate_condition_params)):
	var effect = EffectConsume.new(Effect.new())
	var condition = effect.evaluate_condition(params.get_unit.call(), params.get_rng.call())
	assert_eq(condition, params.expected_res, params.test)
```
As you can see the variable `rng` is populated in the `before_all` function, while `player_unit` in the `before_each`, and therefore they are both null until runtime. But I need `rng` to be valid to initialize the variables of type `Unit`, who requires it in their constructor; and also they are parameters to the function I am testing (`evaluate_condition`).

Let me know if you have another solution to my problem, I am open to suggestions.

Thank you for your time and have a nice day 👋 
Matteo

**Comment by MikeSchulze** [comment]
I do actual a small test to evaluate how to achieve this, and it should be possible to resolve the test parameters without using extra callable.
The actual problem is just the parameters hold by the test suite instance are not propagated to the test parameter resolver.
 
 So looks like it would be easy to solve it ;)

**Comment by Vacui** [comment]
Glad you are making progress 💪 
I can see the node C is correctly created, and if I try to reproduce this test, it expectedly does not work in the current version of GdUnit4 👍
