### ISSUE TITLE
GD-363: Parameterized test stopped working due to test_case names having invalid size

### ISSUE THREAD

**Issue by Vacui** [MikeSchulze/gdUnit4#363]
### The used GdUnit4 version

4.2.2 (Pre Release/Master branch)

### The used Godot version

v4.2.1.stable.official [b09f793f5]

### Operating System

Windows 10

### Describe the bug

I know this is not a bug on an official release, but I wanted to warn you that after replacing my local _gdUnit4_ that was installed from the **AssetLib**, with the version from the **master** branch bearing the changes to solve the issue GD-359, one of my tests stopped working, showing the following error:
```
line 12: Internal Error:
	The resolved test_case names has invalid size!
	Please report this issue as a bug!
```

### Steps to Reproduce

This is my test that stopped working, unfortunately it references other code unique for my game, and therefore it would be difficult to provide generic steps 😅

```gdscript
class_name LogServiceTest
extends GdUnitTestSuite

class TestClass:
	pass

@warning_ignore("unused_parameter")
func test_register(
	test: String,
	type,
	log_level,
	expected_logs,
	test_parameters = [
		["level not registered if type is NOT valid", null, LogService.LogLevel.LOG, {}],
		[
			"level registered if log_level not provided",
			TestClass,
			null,
			{TestClass: LogService.LogLevel.ERROR}
		],
		[
			"level registered if type is valid",
			TestClass,
			LogService.LogLevel.LOG,
			{TestClass: LogService.LogLevel.LOG}
		]
	]
):
	var log_service = LogService.new()
	if log_level == null:
		log_service.register(type)
	else:
		log_service.register(type, log_level)
	assert_dict(log_service._logs).is_equal(expected_logs).override_failure_message(test)
```

**Comment by MikeSchulze** [comment]
Oh! This is related to my latest changes, thanks for reporting this issue.
I was afraid that I might break something and had already installed this error message as a precaution.

**Comment by Vacui** [comment]
Glad to have been of help.
Very cautious of you to add that comment 👍
