### ISSUE TITLE
GD-365: Change the runtest scripts to refer to the script with res:// so that settings to exclude addons from strict type checking takes effect

### ISSUE THREAD

**Issue by vikerman** [MikeSchulze/gdUnit4#365]
### The used GdUnit4 version

4.2.1 (Latest Release)

### The used Godot version

v4.2.1

### Operating System

Linux

### Describe the bug

This is the issue to track the fix mentioned in the github actions repo - https://github.com/MikeSchulze/gdUnit4-action/issues/19

When calling the GDScript scripts in runtest.sh/.cmd the path of the script should start with res:// so that the setting to `Exclude Addons` in Debug>GDScript for excluding stricvt type checks take effect.

### Steps to Reproduce

Run CI tests in GitHub Actions

### Minimal reproduction project

Test repo - https://github.com/vikerman/GDUnitTest

Sync to https://github.com/vikerman/GDUnitTest/commit/d62734037

Tests will fail in Github Actions because of type errors even though the setting to ignore type errors in Addons is on (by default)

**Comment by vikerman** [comment]
Sending a PR for the fix...

**Comment by MikeSchulze** [comment]
Good catch 👍
