### ISSUE TITLE
GD-42: Update Documentation for Install the plugin in an existing C# project

### ISSUE THREAD

**Issue by bbbscarter** [MikeSchulze/gdUnit4#377]
### The used GdUnit4 version

4.2.2 (Latest Release)

### The used Godot version

 v4.2.1.stable.mono.official [b09f793f5]

### Operating System

MacOs 14.4 M1 Mac.

### Describe the bug

After installing from AssetLib, the plugin fails to load with the following errors:

```
CS0246: The type or namespace name 'GdUnit4' could not be found (are you missing a using directive or an assembly reference?) addons/gdUnit4/src/mono/GdUnit4CSharpApi.cs(4,7)

CS0246: The type or namespace name 'GdUnit4' could not be found (are you missing a using directive or an assembly reference?) addons/gdUnit4/src/mono/GdUnit4CSharpApi.cs(15,16)
```

I've since tried later versions via manual installation, but have not been successful.

### Steps to Reproduce

- Install the plugin.
- Activate the plugin.
- Observe the issue.

**Comment by MikeSchulze** [comment]
Which Godot version you are using?
Please fill in the full version information.

I guess you are using the Godot mono version without a c# project, if you run Godot Mono you need to create the c# project.

**Comment by bbbscarter** [comment]
>
> Please fill in the full version information.

Oh, my apologies - I thought I had! v4.2.1.stable.mono.official [b09f793f5]

I guess you are using the Godot mono version without a c# project, if you
> run Godot Mono you need to create the c# project.

I have a C# project - in that I've got other C# code in the project.

But this pointed me in the right direction - I needed to install/activate
the plugin and then *re-create* the C# project after, and then everything
worked.

Thanks!

Unless I missed it, is it worth adding this step to the docs? I'm happy to
do that if it's helpful!

**Comment by MikeSchulze** [comment]
Feel free to improve the documentation ;)
here is the repository https://github.com/MikeSchulze/gdUnit4/tree/documentation

**Comment by bbbscarter** [comment]
Hmm, pre-caffeine brain spoke too soon; regenerating the csproj didn't fix
it.

What *did* fix it was properly reading the C# section of the manual, which
I had missed, and manually adding the required bits the .csproj, as
described here: https://mikeschulze.github.io/gdUnit4/faq/C%23/

Silly me. My apologies, and thanks!

Simon

**Comment by MikeSchulze** [comment]
ok no problem, i will close it as clarified
