### ISSUE TITLE
GD-378: Mock function has or has not been called, regardless of parameters

### ISSUE THREAD

**Issue by Vacui** [MikeSchulze/gdUnit4#378]
**Is your feature request related to a problem? Please describe.**
It is more about a need than a problem.

**Describe the solution you'd like**
Right now we have a way to know if:
* there has been at least 1 interaction in the entire mock
* there has been a specific interaction on a specific function in the mock, a specific amount of times

I feel the lack of a way to check if a specific function has been or has not been called, regardless of its inputs.

Why?

Because sometimes you can not predict correctly the inputs of a function or you simply want to assess that the code has never, for any reason, reached the call to that function.

This check would not count as verifying the interaction with the function.

**Describe alternatives you've considered**
Performing various checks on what that function would have done if it were called would not require this new tool but at the cost of more complex tests.

**Additional context**
Here is a snippet of code that I think could help understand my request:
```
class TestClass:
	func condition() -> bool:
		return TestGameController.is_game_started()

	func remove_something():
		if not condition():
			return

		var row := 15
		var column := 20
		TestGameController.remove(row, column)
```
In this case, if we do not think of `row` and `column` as constants, but as a product of some operation performed internally by the function, it would be hard to produce them in the test code to effectively verify that the function `remove` has not been called with those parameters. And that is when the two generic "has_not_been_called" and "has_been_called" would come in handy.
And we can not use `verify_no_interactions` because there is a call to `is_game_started`.
We _could_ verify that the function `is_game_started` has been called, and then assert that no unverified calls have been performed, but that would force us to know all the calls of every nature to other functions of the `TestGameController` before the one we want to verify (which gets out of control when this object is shared between utils), while also obscuring the test in the process (we are not checking that this function has **not** been called, but that, removed all expected calls, there are none others, implicitly stating that this has not been called).

**Comment by MikeSchulze** [comment]
> I feel the lack of a way to check if a specific function has been or has not been called, regardless of its inputs.

You can use argument matchers to achieve this.
e.g. ` verify(mock, 2).remove(any_int(), any_int())` it tests the function `remove` is called two times with any int arguments.

Checkout the [documention](https://mikeschulze.github.io/gdUnit4/advanced_testing/argument_matchers/)

**Comment by Vacui** [comment]
Neat, I will try it immediately

**Comment by Vacui** [comment]
They work like a charm, sorry for bothering you 👍

**Comment by MikeSchulze** [comment]
No problem, you can also join the Discord server to ask questions, typically you will get a quick response.

close as clarified
