### ISSUE TITLE
GD-38: Spy Missing Interactions on Parent Class

### ISSUE THREAD

**Issue by FeralBytes** [MikeSchulze/gdUnit4#38]
**The used Godot version:**
v4.0.beta4.official [e6751549c] Vulkan AKA Forward+

**OS including version:**
OS: Linux Mint 20.3 Cinnamon 5.2.7
Kernel: 5.4.0-131-generic
CPU: AMD Ryzen 9 3900X 12-Core Processor × 12
GPU: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5700 XT]

**Describe the bug**
Spy does not count interactions on the parent class, so verify can not be used correctly.

**Steps to Reproduce**
1. Make a method that calls a parent class method within it.
2. Create a test for the method and verify all of the interactions to include the parent class method that was called.
3. Observe the test fails as if the parent method was never called.

**Minimal reproduction project:**

[GDUnit4MissingInteractions.zip](https://github.com/MikeSchulze/gdUnit4/files/9999553/GDUnit4MissingInteractions.zip)

**Comment by MikeSchulze** [comment]
i now this already this bug comes with the GdScript 2.0 changes that not allows anymore to overwrite functions

Close as duplicate to GD-8

**Comment by FeralBytes** [comment]
Reference #8  Thank you.
