### ISSUE TITLE
GD-385: runtest.sh does not work if GODOT_BIN path contains spaces

### ISSUE THREAD

**Issue by dsychin** [MikeSchulze/gdUnit4#385]
### The used GdUnit4 version

4.2.2 (Latest Release)

### The used Godot version

v4.2.1.stable.official [b09f793f5]

### Operating System

Pop!_OS 22.04 LTS x86_64

### Describe the bug

When running the provided `runtest.sh` file with a GODOT_BIN path that contains spaces, I get the following error.

```bash
export GODOT_BIN='/home/REDACTED/.local/share/Steam/steamapps/common/Godot Engine/godot.x11.opt
.tools.64'
./addons/gdUnit4/runtest.sh
```

```
./addons/gdUnit4/runtest.sh: 9: /home/REDACTED/.local/share/Steam/steamapps/common/Godot: not found
Run tests ends with 127
./addons/gdUnit4/runtest.sh: 13: /home/REDACTED/.local/share/Steam/steamapps/common/Godot: not found
```

This can be fixed by surrounding the usage of GODOT_BIN with quotes.

```bash
#!/bin/sh

if [ -z "$GODOT_BIN" ]; then
    echo "'GODOT_BIN' is not set."
    echo "Please set the environment variable  'export GODOT_BIN=/Applications/Godot.app/Contents/MacOS/Godot'"
    exit 1
fi

"$GODOT_BIN" --path . -s -d res://addons/gdUnit4/bin/GdUnitCmdTool.gd $*
exit_code=$?
echo "Run tests ends with $exit_code"

"$GODOT_BIN" --headless --path . --quiet -s -d res://addons/gdUnit4/bin/GdUnitCopyLog.gd $* > /dev/null
exit_code2=$?
exit $exit_code

```

### Steps to Reproduce

Example:
1. Save Godot's binary to a path which contain spaces and set the GODOT_BIN environment variables.
2. Run the `runtest.sh` script.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.
