### ISSUE TITLE
GD-387: Float Fuzzer

### ISSUE THREAD

**Issue by kdavis** [MikeSchulze/gdUnit4#387]
**Is your feature request related to a problem? Please describe.**
I think a core implementation of a float fuzzer is a good idea

**Describe the solution you'd like**
```
func test_foo(fuzzer := Fuzzers.rangef(0, 1)):
    assert_float(fuzzer.next_value()).is_between(0, 1)
```

**Describe alternatives you've considered**
A custom one for a project, but I feel if a core one exists, everyone can benefit

**Additional context**
n/a

**Comment by MikeSchulze** [comment]
👍
