### ISSUE TITLE
GD-399: Typo in first argument at `GdUnitStringAssert#has_length`

### ISSUE THREAD

**Issue by AlixBarreaux** [MikeSchulze/gdUnit4#399]
**Describe What**
Change an argument typo mistake.

**Describe Why**
The typo mistake is confusing while reading autocompletion.

**Dev hints**
_res://addons/gdUnit4/src/GdUnitStringAssert.gd_

`func has_length(lenght: int, comparator: int = Comparator.EQUAL) -> GdUnitStringAssert:
    return self`

Argument is named len**ght**, not len**gth** but should be.

**Comment by MikeSchulze** [comment]
Thanks for reporting 👍
