### ISSUE TITLE
GD-403: Set Godot `mainloop` to paused results into endless running tests.

### ISSUE THREAD

**Issue by qwertynerd97** [MikeSchulze/gdUnit4#403]
### The used GdUnit4 version

4.2.2 (Latest Release)

### The used Godot version

v4.2.1

### Operating System

Fedora 39

### Describe the bug

When a test suite ends with the game tree paused, the test runner remains open in the background even though all tests have been completed.  This means that users have to manually press the stop button in the testing UI in order to get details about succeeded and failed tests.

### Steps to Reproduce

1. Load the test project (using Godot Mono)
2. Run the single test
3. See that the test window remains open, and that the GdUnit4 Inspector is still in running state, even though the single test is complete
4. Comment out the last two lines of the test
5. Run the test again
6. See that the test window successfully closes after tests are complete

### Minimal reproduction project

[UnpausableTests.zip](https://github.com/MikeSchulze/gdUnit4/files/15046538/UnpausableTests.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.

At first, you are using the assert API in a wrong way
`AssertBool(runner.Scene().GetTree().Paused).Equals(false);`
Please read the documentation carefully.
Correct is:
`AssertBool(runner.Scene().GetTree().Paused).IsTrue();`


But yes there is a bug, I'm able to reproducible:
```cs
namespace GdUnit4.Tests.Issues;

using Godot;

using static Assertions;


[TestSuite]
public class Issue403Test
{
    [TestCase]
    public void HangsWhenPaused()
    {
        var mainLoop = (SceneTree)Engine.GetMainLoop();

        AssertBool(mainLoop.Paused).Equals(false);

        // The following lines cause the GdUnit4 test window to remain open even after tests
        // are complete
        mainLoop.Paused = true;
        AssertBool(mainLoop.Paused).IsTrue();
    }


    [TestCase]
    public void AfterHangsWhenPaused()
        => AssertBool(true).IsFalse();
}
```

It only occurs when running inside Godot editor, using Visual Studio Code it works fine.

**Comment by MikeSchulze** [comment]
Up

**Comment by MikeSchulze** [comment]
You modify an Engine state, in this case the main loop.
Set the main loop to paused will truly stop the engine running, so the test execution where is running in the main loop also is paused.

When you modify Engine states, you need to ensure you restore it to the previous value when your test is finished.

You can archive this by adding the test after stage to your test suite.
```
	[AfterTest]
	public void TearDown() =>
		// reset pause state back to default
		((SceneTree)Engine.GetMainLoop()).Paused = false;
``` 

Your test suite should look like:
```
namespace GdUnit4.Tests.Issues;

using Godot;

using static Assertions;


[TestSuite]
public class Issue403Test
{

	[AfterTest]
	public void TearDown() =>
		// reset pause state back to default
		((SceneTree)Engine.GetMainLoop()).Paused = false;


	[TestCase]
	public void HangsWhenPaused()
	{
		var mainLoop = (SceneTree)Engine.GetMainLoop();

		AssertBool(mainLoop.Paused).Equals(false);

		// The following lines cause the GdUnit4 test window to remain open even after tests
		// are complete
		mainLoop.Paused = true;
		AssertBool(mainLoop.Paused).IsTrue();
	}


	[TestCase]
	public void AfterHangsWhenPaused()
		=> AssertBool(true).IsFalse();
}
```
