### ISSUE TITLE
GD-408: A Lot of errors after first install and activate from the `AssetLib`

### ISSUE THREAD

**Issue by ZodmanPerth** [MikeSchulze/gdUnit4#408]
### The used GdUnit4 version

4.2.0

### The used Godot version

v4.2.1.stable.official [b09f793f5]

### Operating System

Windows 11

### Describe the bug

Installing from the AssetLib and activating the plugin (as per the installation instructions) does not install the plugin correctly.  Many errors are shown and the GdUnit tab does not appear.
I have tried uninstalling, cleaning the folder, closing and reopening Godot before installation but that doesn't work either.

### Steps to Reproduce

Example:
1. Follow the installation instructions for installing from the AssetLib
5. Observe errors in the console.

### Minimal reproduction project

[console output.txt](https://github.com/MikeSchulze/gdUnit4/files/15055278/console.output.txt)

**Comment by ZodmanPerth** [comment]
I have the errors every time I restart.  Here's my installation process:

* delete previous install from addons folder
* restart Godot
* download and install gdUnit from AssetLib
* restart Godot
* enable gdUnit in project
* restart Godot
* observe errors
* restart Godot (again)
* observe errors

**Comment by ZodmanPerth** [comment]
Ah, I had to delete the contents of my `.godot/imported` and restart Godot before the errors would stop and the gdUnit tab would be created.

**Comment by MikeSchulze** [comment]
> Ah, I had to delete the contents of my `.godot/imported` and restart Godot before the errors would stop and the gdUnit tab would be created.

Yes, Godot still has a problem with its own cache, unfortunately sometimes you just have to hard clear the cache.
It's a shame that the Godot developers can't finally get this solved.
