### ISSUE TITLE
GD-413: Classes with enum in their constructor cannot be spied on

### ISSUE THREAD

**Issue by Vacui** [MikeSchulze/gdUnit4#413]
### The used GdUnit4 version

4.2.4

### The used Godot version

v4.2.1.stable.official [b09f793f5]

### Operating System

Win 10

### Describe the bug

Can not spy Classes that has Enums in their constructor.

### Steps to Reproduce

Example constructor:
```gdscript
class ExampleClass:
enum Rarity { NONE, COMMON, RARE }
func _init(rarity: Rarity) -> void:
```
If you try to spy it this way:
```gdscript
var x = ExampleClass.new(ExampleClass.Rarity.COMMON)
var x2 = spy(x)
```
It throws this error:
```
Invalid type in function '_init'. Cannot convert argument 1 from Nil to int.
```

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug
