### ISSUE TITLE
GD-414: Spy test on enum constructor is unclear

### ISSUE THREAD

**Issue by Vacui** [MikeSchulze/gdUnit4#414]
**Describe What**
The latest test on the spy feature, coded to check a class with enum constructor is not clear to read.

**Describe Why**
It uses elements that are unique of another implementation and does not fit gdUnit4.

**Dev hints**
N/A

**Comment by Vacui** [comment]
Sorry, this is my first time trying to contribute to the project.
I am trying to follow the guide but I do not know how to assign myself 😅
I have already forked the project and fixed the issue 👍

**Comment by MikeSchulze** [comment]
Can you explain what is unclear in more detail please?

**Comment by Vacui** [comment]
I published a PR with my suggested changes: https://github.com/MikeSchulze/gdUnit4/pull/415
But to summarize, I found that using types such as `UnitPreset` was not fitting of GdUnit4 and could alienate when read in the future. For testing purposes I think a more descriptive name such as `EnumValue` would be better.

**Comment by MikeSchulze** [comment]
> But to summarize, I found that using types such as `UnitPreset` was not fitting of GdUnit4 and could alienate when read in the future. For testing purposes I think a more descriptive name such as `EnumValue` would be better.

Yes, you are right, it makes sense 👍 
I have added some comments to your PR.

**Comment by Vacui** [comment]
@MikeSchulze if you push an hotfix can you also rename the variable `unit`, I forgot to change that.

**Comment by MikeSchulze** [comment]
> @MikeSchulze if you push an hotfix can you also rename the variable `unit`, I forgot to change that. Something like `instance` as you did in the other tests.

Too late, ;) it already pushed.
