### ISSUE TITLE
GD-443: Errors in output panel when the `gdunit` inspector dock is floating.

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#443]
### The used GdUnit4 version

4.2.5 (Latest Release)

### The used Godot version

V4.2.2 stable official

### Operating System

macOS : Sonoma 14.4.1

### Describe the bug

Errors in the output panel when I make the dock floating
 

>  scene/main/node.cpp:1450 - Condition "p_child->data.parent != this" is true.
>   scene/main/node.cpp:1450 - Condition "p_child->data.parent != this" is true.

Same errors occured when the panel go back to its dock position when I closed it.

When the dock is floating and you launch a bunch of tests, you got the following error:

>   res://addons/gdUnit4/src/ui/GdUnitInspector.gd:14 - Trying to assign value of type 'MarginContainer' to a variable of type 'TabContainer'.

### Steps to Reproduce

1. Make the Gdunit dock floating
2. Look in the output panel to see the first set of errors
3. Launch some tests to the second error inside the output panel
4. Close the floating Gdunit panel to see the last set of errors in the output panel

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug.
