### ISSUE TITLE
GD-444: Duplicate menu entries when you dock and undock the `gdunit` inspector

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#444]
### The used GdUnit4 version

4.2.5 (Latest Release)

### The used Godot version

V4.2.2 stable official

### Operating System

macos : Sonoma 14.4.1

### Describe the bug

When you dock and undock the gdunit panel, the test menu entries are duplicated.
<img width="340" alt="image" src="https://github.com/MikeSchulze/gdUnit4/assets/15327047/1d3b135c-2301-410c-82ca-b6bf5999e1b4">
<img width="340" alt="image" src="https://github.com/MikeSchulze/gdUnit4/assets/15327047/f3de0e48-bf5e-46b8-9e2f-ea7505491c7c">

### Steps to Reproduce

Dock and undock the gdunit panel several times and right click in the script editor to see the bug

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug.
