### ISSUE TITLE
GD-451: Invalid test class name generated

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#451]
Today if your class name and extends are on the same line like bellow

`class_name MyClass extends Node`

The name for the class test will `MyClassextendsNodeTest`. I feel it's not user-friendly.

The name should be `MyClassTest`, it's more human-readable :).

**Comment by MikeSchulze** [comment]
This is a bug, the name should be near to the source class, e.g. `MyClassTest`
