### ISSUE TITLE
GD-452: Window close button don't work in the parameters dialog

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#452]
### The used GdUnit4 version

4.2.5 (Latest Release)

### The used Godot version

V4.2.2 stable official

### Operating System

MacOs : Sonoma 14.4.1

### Describe the bug

When you click on the window close button of the parameter dialog nothing happen
![image](https://github.com/MikeSchulze/gdUnit4/assets/15327047/5e2516b6-b2f6-49f1-a6b3-8216b32e4a0f)

I suspect that the signal close_requested is not handled in this case

### Steps to Reproduce

Open the inspector parameter and try to close the dialog with the window button

### Minimal reproduction project

None

**Comment by MikeSchulze** [comment]
I know this issue ;)
But you can close it by using the close button in the bottom right.
