### ISSUE TITLE
GD-454: Tests skipped when type is precised in the test function

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#454]
### The used GdUnit4 version

4.2.5 (Latest Release)

### The used Godot version

V4.2.2 stable official

### Operating System

Sonoma 14.4.1

### Describe the bug

Tests are skipped in parameterized tests, if the parameters of the test function are typed and the parameterized data contains objects or null

### Steps to Reproduce

```
func test_good_owner(p_resource: RPGResource, test_parameters: Array = [
						[RPGMap.new()],
						[RPGEquipment.new()],
											]) -> void:

pass
```
RPGMap and RPGEquipment are child of RPGResource
the error message is :
This test is skipped!
  Reason: '
	The parameter set at index [0] does not match the expected input parameters!
	The value '<Resource#-9223371933289019745>' does not match the required input parameter <p_resource:Variant>.'

if I remove the type of p_resource, it works.

I got the same error, if  `null `is inside the test_parameter .

**Comment by MikeSchulze** [comment]
The parameterized parsing do only supports concrete types, it must match with the input parameters.
You can use `Variant` instead.

**Comment by didierGuieu** [comment]
I tried but I got the same error
```
func test_good_owner(p_resource:Variant, test_parameters: Array = [
						[RPGItem.new()],
						[RPGEquipment.new()],
											]) -> void:
```

and the error is :
line 95: This test is skipped!
  Reason: '
	The parameter set at index [0] does not match the expected input parameters!
	The value '<Resource#-9223371932466936163>' does not match the required input parameter <p_resource:Variant>.'

**Comment by didierGuieu** [comment]
The only way to run the test is to remove the type of p_resource

**Comment by MikeSchulze** [comment]
ok I will check this tomorrow.

**Comment by MikeSchulze** [comment]
You need to upgrade to GdUnit4 v4.3 where is not official yet released
![image](https://github.com/MikeSchulze/gdUnit4/assets/347037/8dedab6f-79eb-4de7-a376-c702ae4dffa3)
