### ISSUE TITLE
GD-455: The `gdUnitConsole` shows only the first report

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#455]
Today, when we have several assert in a test, we can only see the first failed assert inside the GdUnit console.
But inside the inspector, we have the full list of failed assert.

I think we shoudl have the same level of details in both view.

I have a second reason, if my undestanding is right, the output of gdunitconsole is the one who is collected inside github action.
it should be nice to have all the failed assert of a test in a glance inside actions also.

Today Inspector view:
<img width="461" alt="image" src="https://github.com/MikeSchulze/gdUnit4/assets/15327047/3a7dc589-ea44-432d-88a3-b71ca74388b4">

today gdunitConsole:
<img width="973" alt="image" src="https://github.com/MikeSchulze/gdUnit4/assets/15327047/246243ae-0b98-4cf9-89ef-64c257a2c979">

**Comment by MikeSchulze** [comment]
Thanks for reporting this, yes the console should show the full list of test failures
