### ISSUE TITLE
GD-460: Add a set_name function to the assert* test

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#460]
Today, when we run a test with many assert inside the same test and when it fails, we have this kind of message :
```
line <n/a>: Expecting:
 '1'
 but was
 '-5'
```

But which assert failed ?

with a set-name function:
assert(my_var).set_name("my_var").is_equal(5)

the expected message should be :
```
line <n/a>: my_var expecting:
 '1'
 but was
 '-5'
```

**Comment by MikeSchulze** [comment]
Hi,
You can just run the test in debug mode, and you will get the failing line number to jump on.
Just adding a variable name could also not help when you are testing the same variable in a test multiple times.

**Comment by didierGuieu** [comment]
Make sense.
It was just a UX improvment.

**Comment by MikeSchulze** [comment]
> Make sense. It was just a UX improvment.

all good :) am always open to improvements but in this case it is unnecessary
