### ISSUE TITLE
GD-457: Documentation Sidebar Not Usable When Using Mobile Device

### ISSUE THREAD

**Issue by olinic** [MikeSchulze/gdUnit4#461]
**What**
Documentation sidebar is not usable when using a small screen (i.e., mobile device).
![image](https://github.com/MikeSchulze/gdUnit4/assets/5348193/6bfcb7d4-cd0b-4345-8881-e3629d4b587a)

**Why**
Almost everyone uses a mobile device. Support mobile device users will improve the usage of gdunit.

**Comment by MikeSchulze** [comment]
Nice catch 👍
