### ISSUE TITLE
GD-465: Parameterized tests are skipped with const Array values

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#465]
### The used GdUnit4 version

4.2.5 (Latest Release)

### The used Godot version

V4.2.2 stable official

### Operating System

Sonoma 14.4.1

### Describe the bug

I got this error when i used an array of const array in parametized tests.

<img width="431" alt="image" src="https://github.com/MikeSchulze/gdUnit4/assets/15327047/97ba2e88-2414-48b3-8717-768aa6cfd7a8">

```
line 12: This test is skipped!
  Reason: 'Internal Error:
	The resolved test_case names has invalid size!
	Please report this issue as a bug!
```

see the steps to reproduce to have a minimum repro project.

### Steps to Reproduce

```
class_name StartTest
extends GdUnitTestSuite
@warning_ignore('unused_parameter')
@warning_ignore('return_value_discarded')

#gdlint: disable=unused-argument, private-method-call

const DATA1: Array = [1,2]
const DATA2: Array = [2,3]

func test_ready(p_data: Array, test_parameters: Array = [DATA1, DATA2]) -> void:
	assert_bool(true).is_true()
```

Run this test

**Comment by didierGuieu** [comment]
I was wrong in my test:
it works with 
```
func test_ready(p_data: Array, test_parameters: Array = [[DATA1], [DATA2]]) -> void:
	assert_bool(true).is_true()
```
which is the good syntax.

Not sure about how to qualify the bug...

**Comment by MikeSchulze** [comment]
The argument parser has a problem if no array brackets are used inside the test parameter set.
e.g.
```
var _data1 := ["aa"]
var _data2 := ["bb"]

@warning_ignore("unused_parameter")
func test_with_extern_parameter_set2(value :String, test_parameters := [_data1, _data2]) -> void:
	assert_that(value).is_not_empty()
```
