### ISSUE TITLE
GD-481: hardcoded res://icon.png path

### ISSUE THREAD

**Issue by paskausks** [MikeSchulze/gdUnit4#482]
### The used GdUnit4 version

4.3.0 (Pre Release/Master branch)

### The used Godot version

v4.2.2.stable.official [15073afe3]

### Operating System

Ubuntu Linux 22.04.4

### Describe the bug

First of all, love the project, this is basically just a minor nuisance.

Within GdUnitSettingsDialog.tscn there seems to be a hardcoded path to `res://icon.png`. In projects, which have this file missing will result in an error being pushed on startup in the console `Resource file not found: res://icon.png (expected type: Texture2D)`.

### Steps to Reproduce

1) create new project
2) add gdunit 4.3.0
3) remove default icon.png
4) reload project

**Comment by MikeSchulze** [comment]
Arg that's a mistake introduced with the new logo, thanks for reporting
