### ISSUE TITLE
GD-486: Error in the output console at the startup of the addin

### ISSUE THREAD

**Issue by didierGuieu** [MikeSchulze/gdUnit4#486]
### The used GdUnit4 version

4.3.0 (Pre Release/Master branch)

### The used Godot version

V4.2.2 stable official

### Operating System

MacOS Sonoma 14.5

### Describe the bug

I have the following message inside the output console.

Godot Engine v4.2.2.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
  Invalid image: null
  core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
  Invalid image: null
  core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
  Invalid image: null
  core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
  Invalid image: null
  core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
  Invalid image: null
  core/variant/variant_utility.cpp:1091 - invalid height:16 vs 32
  Invalid image: null
Loading GdUnit4 Plugin success
GdUnit4: Test server successfully started checked port: 31002

### Steps to Reproduce

Just enable the plugin the errors are inside the output console.
I removed .Godot folder and the error is still here

**Comment by MikeSchulze** [comment]
The root cause it Godot icon image size are different on macOS
https://github.com/godotengine/godot/issues/92628
