### ISSUE TITLE
GD-491: segmentation fault when closing godot editor

### ISSUE THREAD

**Issue by Krigu** [MikeSchulze/gdUnit4#492]
### The used GdUnit4 version

4.3.1 (Latest Release)

### The used Godot version

v4.2.2.stable.arch_linux

### Operating System

Manjaro Linux

### Describe the bug

We are using GdUnit in our build pipeline and after updating to GdUnit 4.3.0, the godot editor does not exit properly when closing the editor. 

This is proplematic because we are checking for the exit status of the godot process during the build. We expirienced the same behaviour when using GdUnit 4.3.1

### Steps to Reproduce

I was able to reproduce the error without the command line tools in a clean project. 

1. Start godot via command line with `godot . -e`
2. Created a new project in Godot 4.2.2
3. Added gdUnit Plugin 4.3.1 and activate it under Project Settings -> Plugins
4. Close project

=> The terminal is showing "Unload GdUnit4 Plugin success", but it also shows a segmentation fault and the process exits with error code 139 and following console output is shown. 

> Loading GdUnit4 Plugin success
GdUnit4: Test server successfully started checked port: 31002
ERROR: Parent node is busy adding/removing children, `remove_child()` can't be called at this time. Consider using `remove_child.call_deferred(child)` instead.
   at: remove_child (scene/main/node.cpp:1449)
ERROR: Condition "data.parent" is true.
   at: ~Node (scene/main/node.cpp:3583)
ERROR: Parent node is busy adding/removing children, `remove_child()` can't be called at this time. Consider using `remove_child.call_deferred(child)` instead.
   at: remove_child (scene/main/node.cpp:1449)
ERROR: Condition "data.parent" is true.
   at: ~Node (scene/main/node.cpp:3583)
Unload GdUnit4 Plugin success
zsh: segmentation fault (core dumped)  godot . -e

When disabling the plugin and closing the project, no error gets shown.

**Comment by MikeSchulze** [comment]
https://github.com/godotengine/godot/issues/92727

**Comment by MikeSchulze** [comment]
@Krigu can you please check out the master and verify if it's working as expected now?

**Comment by MikeSchulze** [comment]
@Krigu can you please check out the master and verify if it's working as expected now? I have no Linux system to can test direct, but from the GitHub action it runs without crash.

**Comment by Krigu** [comment]
@MikeSchulze Sorry for the late response, I was offline for a couple days. 

I checked with the current master on my machine (Linux Manjaro) and everything seems to work as expected now. Thanks for fixing it so quickly!
