### ISSUE TITLE
GD-529: Cannot call method 'get_meta' on a null value

### ISSUE THREAD

**Issue by JoelCreatesGames** [MikeSchulze/gdUnit4#529]
### The used GdUnit4 version

4.3.3 (Pre Release/Master branch)

### The used Godot version

v4.2.1.stable.official [b09f793f5]

### Operating System

Windows 11

### Describe the bug

In the GdUnit Dock sometimes when right clicking on a test to run/debug it won't work and result in an error in the output. If I select something else, and then try again it will work. It doesn't always happen, but I have a suspicion its related to saving the test script

![image](https://github.com/MikeSchulze/gdUnit4/assets/62071362/f612b626-4c2e-46e4-b254-e17815415de9)

![image](https://github.com/MikeSchulze/gdUnit4/assets/62071362/b92bccf0-9d23-40fe-b90a-0aeb432bcc4f)

### Steps to Reproduce

1. Open the application to the GdUnit dock.
2. Right click a test and debug.
3. Make some changes to the test script and save with ctrl+s.
4. Right click a test and debug.
5. Observe the error in the console (sometimes, not always).

**Comment by MikeSchulze** [comment]
Hi, thanks for reporting, but I'm not able to reproduce.

Can you please describe in more detail:
a) your gdunit4 settings
  - auto test discovery on or off
  - test root directory
b) attach a test suite to reproduce 
- describe what you have change before save

**Comment by JoelCreatesGames** [comment]
That didn't actually fix it, just changed the error. It seems related to the tree view and selecting it fresh between test runs. 

[2024_07_04_0.webm](https://github.com/MikeSchulze/gdUnit4/assets/62071362/210bdafa-6886-4d5a-b515-0f9fb0fe23ad)

**Comment by MikeSchulze** [comment]
It occurs only in Godot v4.2.1 and seems to be related to https://github.com/godotengine/godot/pull/88917
