### ISSUE TITLE
GD-533: GdUnit4 shows errors `Trying to assign value of type 'Nil' to a variable of type 'Color'` on a fresh Godot installation at loading `TestSuiteTemplate`.

### ISSUE THREAD

**Issue by SrdanJokic** [MikeSchulze/gdUnit4#533]
### Background
This is partially related to #499, namely the errors
```
editor/editor_settings.cpp:221 - EditorSettings::_get - Property not found: text_editor/theme/highlighting/gdscript/annotation_color
res://addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd:57 - Trying to assign value of type 'Nil' to a variable of type 'Color'.
editor/editor_settings.cpp:221 - EditorSettings::_get - Property not found: text_editor/theme/highlighting/gdscript/annotation_color
res://addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd:57 - Trying to assign value of type 'Nil' to a variable of type 'Color'.
```
which occur on every startup. I've followed the advice and deleted the .godot folder and rebuilt/restarted the project multiple times, however, the error still persisted. I saw that the script was trying to access the `annotation_color` property of editor settings, which, for some reason, were not present in my project. 

Upon investigating further, I discovered that these `/gdscript` properties are only generated if the internal Godot script editor has been used at least once - which wasn't the case for our project since we instantly swapped to C# with VSCode/Rider without ever using the internal script editor, causing the attributes to never be generated, resulting in the errors above on every startup.

### Precise reproduction steps

1. Create a new project
2. Install GdUnit4, activate, restart
3. Create a test and run 
No script errors, the tests run as expected
4. Close all scripts the script list inspector must be empty
5. Close Godot
6. Delete the user data Godot main folder e.g. windows `C:\Users\name\AppData\Roaming\Godot\`
7. Open Godot and import the project
It shows initial the script errors

This can be resolved by setting the "Use External Editor" to false, opening a gdscript in the internal editor and letting Godot generate the `annotation_color` attribute, however, this is not ideal towards the end users.

### Description

The task should remove the dependency on `/gdscript` colors to ensure that all projects without the `/gdscript` properties are not facing the mentioned error. 

### Acceptance criteria

The missing color issues no longer appear for existing and new C# projects when following the reproduction steps above.

**Comment by MikeSchulze** [comment]
Hi thanks for reporting, but i'm not able to reproduce.
Can you please add the missing informations.
a) used Godot version
b) used GdUnit4 version


I have set the extrnal editor to Rider and it openes the GDScript and C# sripts in Rider now.
I see no script errors in Godot.
![image](https://github.com/MikeSchulze/gdUnit4/assets/347037/d1638551-3107-4b64-a4e4-e99fbfac0a61)

I also do save a custom test-suite template, but i can't reproduce this issue
![image](https://github.com/MikeSchulze/gdUnit4/assets/347037/278a3263-c7e3-404e-9498-88806f2c4567)


can you please attach an example project to reproduce

**Comment by SrdanJokic** [comment]
Hello,

Thanks for the quick response on this. Upon attempting to re-reproduce it, I was unable to repeat the behavior which led me to believe this setting isn't project specific but installation-specific instead. 

With that in mind, I deleted the location where Godot permanently stores user (developer) settings on each machine. In my case, this was ~/Library/Application Support/Godot (on MacOS) and the issue re-appeared after re-opening Godot. I think if you delete the said folder (or the windows equivalent of User Preferences directory) you should be able to reproduce the issue in any project.

With that in mind, I no longer think that this issue affects only users who have never opened the internal Scripts tab for the current project, but for users that have never opened it in Godot in the first place.

Let me know if you're still unable to reproduce the issue, and thanks again for a quick response. In case you still need the info:
- Godot version: 4.2.2
- GDUnit version: 4.2.5.0 (even though it was updated via "what's changed" menu to 4.3.3 but that might be a separate issue)

**Comment by MikeSchulze** [comment]
If I delete the Godot folder with the user data, I can reproduce the problem. Thank you, that was the crucial hint.

```
Godot Engine v4.2.2.stable.mono.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Der Blend-Dateiimport ist in den Projekteinstellungen aktiviert, aber es wurde kein Blender-Pfad in den Editoreinstellungen festgelegt. Es werden keine Blend-Dateien importiert.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  editor/editor_settings.cpp:221 - EditorSettings::_get - Property not found: text_editor/theme/highlighting/gdscript/annotation_color
  res://addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd:57 - Trying to assign value of type 'Nil' to a variable of type 'Color'.
  editor/editor_settings.cpp:221 - EditorSettings::_get - Property not found: text_editor/theme/highlighting/gdscript/annotation_color
  res://addons/gdUnit4/src/ui/templates/TestSuiteTemplate.gd:57 - Trying to assign value of type 'Nil' to a variable of type 'Color'.
GdUnit4: Test server successfully started checked port: 31002
Loading GdUnit4 Plugin success
GdUnit4Net version '4.2.5.0' loaded.

```
