### ISSUE TITLE
GD-539: Settings UI help strings should not include internal data

### ISSUE THREAD

**Issue by mathrick** [MikeSchulze/gdUnit4#539]
**Describe What**
Currently, the settings UI includes internal data used by the code to know what possible options a settings has. This is a consequence of the fact that `ProjectSettings`  does not give an easy way to store that information. But the code should take care to remove those details prior to showing the help to the user.

**Describe Why**
Seeing internal details included in the help string is not useful to the user, and makes the help worse than it could be. They can already see the same information presented as a dropdown, and the help should be as concise as is possible.

**Comment by MikeSchulze** [comment]
👍
