### ISSUE TITLE
GD-540: Improve user-facing help strings in settings UI

### ISSUE THREAD

**Issue by mathrick** [MikeSchulze/gdUnit4#540]
**Describe What**
Improve the settings help by removing unnecessarily verbose and repetitive elements, things which are already obvious from the UI, and ironing out inconsistencies. Make sure the help strings are understandable on their own; currently, some of them are really hard to understand without consulting the docs.

**Describe Why**
Help text is a critical part of the UI, and the more concise and obviously applicable to the UI it is, the more value it has. It should give information the user doesn't have, and not repeat things they already know from seeing the UI. These are pretty well-established principles of good UI text design.

**Comment by MikeSchulze** [comment]
👍
