### ISSUE TITLE
GD-541: Settings dialogue reserves way more horizontal space than it needs, leading to huge scrollbars

### ISSUE THREAD

**Issue by mathrick** [MikeSchulze/gdUnit4#541]
**Describe What**
Currently the settings dialogue uses a very crude estimation of what horizontal space labels need, and also has `custom_minimum_size` hardcoded in the scene. This makes it so that it requests a lot more space than it actually needs from the scrolling container, and that makes huge scrollbars show up unnecessarily. It also makes the components wider than they need to be, so the user has to scroll a lot.

**Describe Why**
It's not great UI if the user has to scroll to see things.

**Comment by MikeSchulze** [comment]
👍
