### ISSUE TITLE
GD-XXX: Spies don't support Callables

### ISSUE THREAD

**Issue by mathrick** [MikeSchulze/gdUnit4#542]
### The used GdUnit4 version

4.3.4 (Pre Release/Master branch)

### The used Godot version

v4.2.2.stable.official [15073afe3]

### Operating System

Linux Mint 20

### Describe the bug

Currently, it doesn't seem it's possible to create a spy on a `Callable`. When I try, it throws an error:

```gdscript
var results = []
var callback = spy(func(x): results.append(x))
````

```
line 567: Godot Runtime Error !
	'at: extract_class_name (res://addons/gdUnit4/src/core/GdObjects.gd:567)'
Error: 'Invalid call. Nonexistent function 'new' in base 'Callable'.'
```

**Comment by MikeSchulze** [comment]
To spy or mock a Callable is not supported.
A spy expects an object instance, please check the documentation.
https://mikeschulze.github.io/gdUnit4/advanced_testing/spy/

**Comment by mathrick** [comment]
In this case, would it be possible to add that support? Should I open a feature request?

**Comment by MikeSchulze** [comment]
> In this case, would it be possible to add that support? Should I open a feature request?

Can you tell me more about your use case?
A local callable inside a test makes no sense in my eyes, so I guessing you want to test at least a function that used as a callable.

**Comment by mathrick** [comment]
Sure, any time I write tests for an API making use of callables, spying makes sense to ensure the protocol is maintained:

```gdscript
func test_resolve_promise():
	var callback = spy(func(x): pass)
	var promise = Promise.new().then(callback)
	promise.resolve(42)
	verify(spy, 1).call(42)
```

In this case I can of course change do all the recording of calls manually, by changing the `pass` part inside the callable, but using spies would be an obvious choice since they already have the functionality to do this kind of thing. In this test I'm not testing any logic *inside* the callable, I'm just testing that the *protocol* the callable is a part of is maintained. This is because the callable is not a part of the code being tested, it's always supplied by the user.

**Comment by MikeSchulze** [comment]
> Sure, any time I write tests for an API making use of callables, spying makes sense to ensure the protocol is maintained:
> 
> ```gdscript
> func test_resolve_promise():
> 	var callback = spy(func(x): pass)
> 	var promise = Promise.new().then(callback)
> 	promise.resolve(42)
> 	verify(spy, 1).call(42)
> ```
> 
> In this case I can of course change do all the recording of calls manually, by changing the `pass` part inside the callable, but using spies would be an obvious choice since they already have the functionality to do this kind of thing. In this test I'm not testing any logic _inside_ the callable, I'm just testing that the _protocol_ the callable is a part of is maintained. This is because the callable is not a part of the code being tested, it's always supplied by the user.

Ok I understand you use case, please create an improvement ticket to allow spy on callable.
And attach this description.
