### ISSUE TITLE
GD-549: Error reported in console when tests are run in a popped-out GdUnit4 window.

### ISSUE THREAD

**Issue by dragonforge-dev** [MikeSchulze/gdUnit4#549]
### The used GdUnit4 version

4.3.3 (Latest Release)

### The used Godot version

v4.3.beta3.official [82cedc83c]

### Operating System

Windows 11 Pro, Version 23H2, OS Build 22631.3880

### Describe the bug

Error "(res://addons/gdUnit4/src/ui/GdUnitInspector.gd:15 - Trying to assign value of type 'MarginContainer' to a variable of type 'TabContainer'.)" thrown when Unit Tests are run while the GdUnit window is popped out from the dock.

### Steps to Reproduce

Example:
1. Select the **GdUnit** tab.
2. Click on the **Dock Position** button. (Three vertical dots.)
3. Click **Make Floating**
4. Click the Run button in the popped out window.

**RESULT:** The following Error appears in the console: res://addons/gdUnit4/src/ui/GdUnitInspector.gd:15 - Trying to assign value of type 'MarginContainer' to a variable of type 'TabContainer'.

**EXPECTED:** No error would appear.

**Comment by MikeSchulze** [comment]
Thanks for reporting this Bug.
