### ISSUE TITLE
GD-550 Mocking native functions does nothing

### ISSUE THREAD

**Issue by ketsebum** [MikeSchulze/gdUnit4#550]
### The used GdUnit4 version

4.3.3 (Latest Release)

### The used Godot version

v4.2.2.stable

### Operating System

Windows11

### Describe the bug

I was following the documentation here: https://mikeschulze.github.io/gdUnit4/advanced_testing/mock/

I was attempting to mock a native function on a TIleMap, and I noticed that I was not receiving the expected value. I reduced the problem down to show that the mock fails to override every native function. There does not appear to be a problem with local implementations being overridden.

Assuming I am not doing something colossally wrong, I imagine that the documentation needs to be updated with this limitation. 

### Steps to Reproduce

Example:
1. Create a test file
2. Create a test that mocks an object with native functions
3. Provide a mock return value for a native function
4. Assert that the function will return that value
5. Run the test

If the issue involves code, please include relevant snippets below:
If we have the following implementation:
```gdscript
extends Node
class_name Basic

func can_overload() -> int:
	return 5
```

The following fails:
```gdscript
var mocked_node := mock(Basic) as Basic
do_return(10).on(mocked_node).get_child_count()
assert_that(mocked_node.get_child_count()).is_equal(10)
```

This doesn't mean that all overrides fail. Here is an example that works:
```gdscript
var mocked_basic := mock(Basic) as Basic
do_return(10).on(mocked_basic).can_overload()
assert_that(mocked_basic.can_overload()).is_equal(10)
```

### Minimal reproduction project

[FailTest.zip](https://github.com/user-attachments/files/16404759/FailTest.zip)

**Comment by MikeSchulze** [comment]
Hi, mocking native function is not possible since the GDScript improvements with Godot 4.x.
According to the Godot core developers, overwriting core functions is no longer supported, so there is no way to mock or spy on core functions anymore, sorry.

**Comment by ketsebum** [comment]
Yeah, I kind of figured that was the reason, when I tried to make a fake class that overrode those functions manually.

However, I think that means the documentation should be updated.

**Comment by MikeSchulze** [comment]
> However, I think that means the documentation should be updated.

Yes, this should be documented to avoid this questions again and again 👍

**Comment by MikeSchulze** [comment]
Documentation is updated!
