### ISSUE TITLE
GD-559: Error when double-clicking directory in test inspector

### ISSUE THREAD

**Issue by poohcom1** [MikeSchulze/gdUnit4#559]
### The used GdUnit4 version

4.3.4 (Latest Release)

### The used Godot version

v4.3.stable

### Operating System

Windows 11

### Describe the bug

Double clicking a directory in the test inspector results in the following error in console, and nothing happens:

```
The object does not have any 'meta' values with the key 'line_number'.
res://addons/gdUnit4/src/ui/parts/InspectorTreeMainPanel.gd:909 - Trying to assign value of type 'Nil' to a variable of type 'int'.
```

https://github.com/user-attachments/assets/472c2f27-48a8-4b70-a4dc-ecf0df803f96

There are two things I think should be changed:
1. This error should not appear in the console.
2. Clicking on a directory should toggle collapse. (opinion)

### Steps to Reproduce

1. Create a gdunit test in a nested directory.
2. Double click on a directory in the inspector.

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue 👍
