### ISSUE TITLE
Print statements appear neither in Output or GdUnitConsole

### ISSUE THREAD

**Issue by adadgio** [MikeSchulze/gdUnit4#571]
### The used GdUnit4 version

4.3.4 (Latest Release)

### The used Godot version

v4.3

### Operating System

Mac OS Sonoma

### Describe the bug

In tests, the print() statement does not print anything in the Ouput tab nor in the GDUnit console. Not sure if this should be reporterd as or intended feature, but that would be very usefull nonetheless to debug tests.

### Steps to Reproduce

Write any test and write a print("Anything you want") statement.

### Minimal reproduction project

[gdunitprintbugreport.zip](https://github.com/user-attachments/files/17040430/gdunitprintbugreport.zip)

**Comment by MikeSchulze** [comment]
> A have a question about mocking autoload singletons and methods, which I couldn't do despite the docs. Where you I ask about that ?

Mocking a autoload is not possible because autoloads are singletons and by default a single instance.

**Comment by MikeSchulze** [comment]
> Sorry, I meant stub a autoload method. Doing do_return on an autoloaded singleton is not possible ?

Please do not ask not issue related questions here, please use the discussions or join the Discord server for direct help. 

This is technical, not possible.
The autoload instance is loaded by Godot and hold by a singleton instance.
You can't build a mock/stub of this, this would need technical to replace the original instance and this is not possible.

**Comment by dmlary** [comment]
@MikeSchulze in 4.5.1 `await get_tree().process_frame` does not work using version 5.0.3, and 6..0.3 of GdUnit4.

Even an arbitrary `await await_millis(250)` wasn't a long enough wait for the print to show up.

Do you have any other ideas for ensuring print() works?

**Comment by MikeSchulze** [comment]
@dmlary there are different point where the print statements not seen in the Godot output console,
1) You are using run mode instead of run in debug mode.
2) Check the Godot log settings are correct

<img width="1198" height="727" alt="Image" src="https://github.com/user-attachments/assets/0cb4a1a6-5646-4a5c-a6e4-649bc9939212" />

<img width="1203" height="733" alt="Image" src="https://github.com/user-attachments/assets/32d2959d-967d-4501-9c08-0496e4a3327e" />

**Comment by dmlary** [comment]
@MikeSchulze You had it right.  At some point when I was fighting with it, I switched from run in debug mode to just run.  Thank you!
