### ISSUE TITLE
GD-596: Command line: Using -i argument results in crash

### ISSUE THREAD

**Issue by drusin** [MikeSchulze/gdUnit4#596]
### The used GdUnit4 version

4.4.1 (Pre Release/Master branch)

### The used Godot version

4.3 stable

### Operating System

Windows 11, ubuntu-latest (on on giuthub)

### Describe the bug

Trying to run gdunit4 tests using the command line tool and passing `-i` to skip a suite always results in:
```
Godot Engine v4.3.stable.official.77dcf97d8 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 537.13 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce GTX 1080 Ti


--------------------------------------------------------------------------------------------------
GdUnit4 Comandline Tool
--------------------------------------------------------------------------------------------------

Scanning for test suites in: C:/dev/godot/gdunitbugreport/test
Found excluded test suite's configured at ''

Debugger Break, Reason: 'Trying to assign an array of type "Array" to a variable of type "Array[String]".'
*Frame 0 - res://addons/gdUnit4/bin/GdUnitCmdTool.gd:410 in function 'skip_suite'
Enter "help" for assistance.
```

I tried the following:
* `.\addons\gdUnit4\runtest.cmd -a .\test -i SuiteToSkip`
* `.\addons\gdUnit4\runtest.cmd -a .\test -i "SuiteToSkip"`
* `.\addons\gdUnit4\runtest.cmd -a .\test -i "suite_to_skip" `
* `.\addons\gdUnit4\runtest.cmd -a .\test -i "suite_to_skip.gd"`
* `.\addons\gdUnit4\runtest.cmd -a .\test -i ".\test\suite_to_skip.gd"`

### Steps to Reproduce

Run tests using the command line tool and try to skip a test suite using the param `-i`

### Minimal reproduction project

[gdunitbugreport.zip](https://github.com/user-attachments/files/17775758/gdunitbugreport.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting, I will take a look soon.
