### ISSUE TITLE
GD-607: GdUnit4 Godot plugin does not find test suites at the root folder

### ISSUE THREAD

**Issue by esainane** [MikeSchulze/gdUnit4#607]
### The used GdUnit4 version

4.4.4 (Pre Release/Master branch)

### The used Godot version

v4.3.1.rc.mono.custom_build [ff9bc0422]

### Operating System

`6.11.5+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian GNU/Linux trixie/sid 6.11.5-1~bpo12+1 (2024-11-11) x86_64`

### Describe the bug

The `gdUnit4` settings description for `Test Lookup Folder` states:

> Subfolder where test suites are located (or empty to use source folder directly)

However, leaving this setting empty (or set to `/`, or `res://`) will cause `gdUnit4` to not find any test suites in the root folder. `scan_test_directories` starts by examining subfolders, though it is very permissive with any of these test directory settings.

This structure would be bad practice in a proper project, since it has to perform a lot of scanning which a dedicated test directory would avoid. However, this should eliminate much confusion when trying to create a minimal reproducible test project, and wondering why the test suite is silently not being detected.

This is not a problem when using the `GdUnit4 Test Adapter` via `VSTest`; tests located in the root folder will be correctly located and executed when going through `VSCode`. This is only an issue when going through the `GdUnit4 Godot Editor plugin`.

### Steps to Reproduce

- Configure `Test lookup folder` in gdUnit4 settings to be blank (or `/`, or `res://`)
- Create a test case in the root directory of the project:
```cs
namespace GDUnit4RootTestExample;

using Godot;
using GdUnit4;

using static GdUnit4.Assertions;

[TestSuite]
public class ExampleTest
{
    [TestCase]
    public void FindMe() => AssertBool(true).IsTrue();
}
```
- Run tests via `VSCode`. Observe `VSCode` finding the test.
- Run tests via `Godot Editor`. Observe `Godot Editor` failing to find the same test.

### Minimal reproduction project

[gdunit4-root-test-example.zip](https://github.com/user-attachments/files/17986418/gdunit4-root-test-example.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting this bug.
