### ISSUE TITLE
GD-609: Change the default update notification mechanism to a less intrusive one

### ISSUE THREAD

**Issue by taikuukaits** [MikeSchulze/gdUnit4#609]
**Is your feature request related to a problem? Please describe.**
I think the default approach of the update notification popup should be replaced with a new mechanism that is less intrusive. Currently I just turn it off in every project and then I lose information about new updates. 

The update popup can be intrusive and get in the way of a normal workflow:
- it's not immediate so it becomes a waiting game to see if I will be interrupted
- sometimes I can't even close the popup until it finishes loading. 
- most of the time I don't even want to update right now, I opened the game to do something else not update gdunit, but I might later

I also don't believe this solution scales. If I had four assets in this project, each using this same approach, it would be even worse. I would get up to four popups whenever I open my project, each telling me about possible updates right away before I am even in my project. This seems undesirable. 

**Describe the solution you'd like**
I would recommend a few changes:
- Do not show the current popup when opening a project.
- Print a message to the log instead on project load "A new version of GDUnit is available". 
- If an update is available, add a button on the GdUnit inspector beneath Errors and Failures "An update is available. Learn more." that I can click on that opens the current popup. 

The log and button should respect the update notification setting. 

**Describe alternatives you've considered**

I know I can skip an individual update in the popup but there seem to be constant releases (which I do appreciate) but that does mean I constantly get this popup even if I select skip this update. It still at least seems like I get a full page popup every time I open my game if I leave the popup on. 

I know I can turn off this popup altogether, but I do like being notified that there are updates and I do like clicking a button to get new update installed automatically. 

**Additional context**
I would be willing to take a crack at implementing this if this is something that would be accepted.

**Comment by MikeSchulze** [comment]
I understand your problem and yes it does make sense to design the update notification differently.
Thanks for the hint, I will think of a solution that does not use a popup to indicate a new update.

**Comment by MikeSchulze** [comment]
I suggest an update notification inside the inspector.
You can press and the original update window will pop up.
https://github.com/user-attachments/assets/bb5d5990-d379-4c55-8fcd-328563018f3e
