### ISSUE TITLE
GD-614: Using un-typed `fuzzer_iterations` parameter, fails to run test as it cannot convert default String value to int to set iterations property

### ISSUE THREAD

**Issue by ChrisTutorials** [MikeSchulze/gdUnit4#614]
### The used GdUnit4 version

4.5.0 (Latest Release)

### The used Godot version

v4.4dev6

### Operating System

Manjaro Linux

### Describe the bug

When trying to use fuzzer_iterations argument in a fuzzer test, the test errors out at line 204 of GdUnitTestSuiteScanner failing to convert the default argument from String to Int.

![image](https://github.com/user-attachments/assets/fac33a13-06d0-412b-bbfe-327df3cf5c5e)

![image](https://github.com/user-attachments/assets/0bc1c03b-48e6-46dd-b3b5-226542460339)

The value I passed into fuzzer_iterations is definitely an int as far as I can tell but somewhere it gets converted to a string before being being expected to assign as an int to the iterations int property.

I notice that adding a int(value) wrapper to this line resolves the error and the test can proceed as expected

![image](https://github.com/user-attachments/assets/7b70ad89-36a3-4b9d-8d1a-076440835519)

### Steps to Reproduce

1. Create Godot Project in 4.4dev6
2. Install gdunit 4.5.0
4. Create script test_iterations.gd with the following code
5. Run the test in debug mode.

```extends GdUnitTestSuite

func test_iterations(fuzzer = Fuzzers.rangef(-100.0, 100.0), fuzzer_iterations = 10):
	assert_float(fuzzer.next_value()).is_between(-100.0, 100.0)

```

### Minimal reproduction project

[iterations_test.zip](https://github.com/user-attachments/files/18141581/iterations_test.zip)

**Comment by MikeSchulze** [comment]
Thanks for reporting this issue.
It looks like there is an issue when using un-typed test parameters.
Use typed parameters as workaround for now.
```
extends GdUnitTestSuite

func test_iterations(fuzzer := Fuzzers.rangef(-100.0, 100.0), fuzzer_iterations := 10):
	assert_float(fuzzer.next_value()).is_between(-100.0, 100.0)

```
