### ISSUE TITLE
GD-8: Using typed assign breaks mocking implementation

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#8]
**The used Godot version:**
v4.0.beta3.official [01ae26d31]

**OS including version:**
All

**Describe the bug**
I want to mock on classes to define a custom return value without need to instanciate the full class.
On Godot 3 I was able to overwrite all functions of an Engine class to trag if is called or not, this is now broken on Godot4.

Like this simple example shows the overwritten function is not called anymore in Godot4.
```
class CustomNode extends Node:
	
	func foo():
		pass


class TestNode extends CustomNode:
	
        # overwrite the orignal Node:is_inside_tree() function 
	func is_inside_tree() -> bool:
		prints("is_inside_tree")
		return true


func _ready():
	var node := TestNode.new()
	node.is_inside_tree()
```

**Steps to Reproduce**
Run testcase `GdUnitMockerTest:test_mock_by_script_path`

## Workaround 
do not cast a mock back to original class type!
use allways 
`var mocked_node = mock(Node)`
and not
`var mocked_node :Node = mock(Node)`

## TODO
renable disabled test cases 
and remove excluded from GdUnitClassDoubler @EXCLUDE_VIRTUAL_FUNCTIONS

## Godot issue
https://github.com/godotengine/godot/issues/55024
https://github.com/godotengine/godot/issues/67461

**Comment by FeralBytes** [comment]
Note the workaround does not work when using Spy for me.

**Comment by MikeSchulze** [comment]
> Note the workaround does not work when using Spy for me.
Your issue is related to the major changes of GDScript 2.0 where not allows to override a core function anymore
https://github.com/godotengine/godot/issues/55024

**Comment by FeralBytes** [comment]
@MikeSchulze I see now the issue. Well it is not the end we can still Spy on our methods so long as they are not core class functions.

**Comment by MikeSchulze** [comment]
Since it is no longer possible to override core functions in Godot 4, I am closing this topic.
To enable GdUnit4 to mock/spy core functions again, a complete rewrite of the doubler is necessary

Followup #42
