### ISSUE TITLE
GD-90: Bundle up files in single folder 

### ISSUE THREAD

**Issue by adamscoble** [MikeSchulze/gdUnit4#90]
Hi Mike,

Firstly thanks for the tool, it's really great!

One feature that would be great to simply excluding gdUnit4 from builds would be contain everything in a single folder. 

One idea is an additional folder in `addons/gdUnit4/` that starts with a period to prevent it being imported in the project (if the contained items don't need to be). You could put `GdUnitRunner.cfg`, `runtest.cmd` and `runtest.sh` in this folder, then excluding gdUnit4 from a build would be as simple as excluding its addons folder and the tests folder.

Obviously it's not difficult excluding the individual files, this just feels a little more nicely contained!

Thanks again!

**Comment by MikeSchulze** [comment]
Hi @adamscoble , if I understand correctly you want to have all GdUnit relevant files only in the plugin folder?
We are talking here only about the three files mentioned, right?
This should not be a problem and easy to implement

**Comment by adamscoble** [comment]
Sorry for the delay, yes exactly! And for anything that shouldn't be imported into the engine, you can create a folder with the `.` prefix for Godot to ignore it completely. (Even though it seems to ignore the files anyway, better to be explicit about it I think.)

Thanks again!
