### ISSUE TITLE
GD-96: use of `EditorPlugin.new()` results in script error since beta16

### ISSUE THREAD

**Issue by MikeSchulze** [MikeSchulze/gdUnit4#96]
**The used Godot version:**
v4.0.beta16.official [518b9e580]

**OS including version:**
ALL

**Describe the bug**
We use on some places `EditorPlugin.new()` to access the editor interface.
But this is broken since beta15/beta16
There is no static accessor of the EditorInterface and needs the plugin instance to access.

**Steps to Reproduce**
```
@tool
extends Control

func _ready():
	var plugin := EditorPlugin.new()

```
results in 
`Parser Error: Native class "EditorPlugin" cannot be constructed as it is abstract.`

**Godot Issue**
https://github.com/godotengine/godot/issues/68685

**Minimal reproduction project:**

**Comment by MikeSchulze** [comment]
What do you want to tell me? Is there a current problem with GdUnit4?

**Comment by JustMog** [comment]
yes [bug.zip](https://github.com/MikeSchulze/gdUnit4/files/12808910/bug.zip)

**Comment by MikeSchulze** [comment]
Your code has nothing to do with the GdUnit4 plugin.
If you want to write your own plugin, you have to follow the official documentation.
https://docs.godotengine.org/en/latest/tutorials/plugins/editor/making_plugins.html

**Comment by JustMog** [comment]
oh i got here from the godot repo somehow without realising i'd left it, no idea how that happened, sorry about that
